### ISSUE TITLE
Custom subs

### ISSUE THREAD

**Issue by ivantodorovich** [Cuevana/storm#1]
First, I want to say awesome work on this! 
I followed Popcorn Time progress before yifi's takeover, and I see you took the idea to another level. Gratz!

One of the things I contributed to PT was the ability to add custom subs from local drive. It would be awesome to be able to do that, since it would allow us to play an episode without having to wait for our language subs to be uploaded.

I'd like to know what's the project contribution policy. Are you planning to accept help from outside?

**Comment by Cuevana** [comment]
That would be a nice featured indeed!
Please, feel free to contribute, we are willing to accept help and get this community friven. Thanks!
