### ISSUE TITLE
Barra de reproduccion visible constantemente

### ISSUE THREAD

**Issue by diegocamarotta** [Cuevana/storm#100]
No se si es comportamiento normal pero note que sin importar donde quede el puntero del mouse la barra de reproduccion no se oculta nunca, tapando parte del video. Tambien note que a veces la barra de reproduccion queda arriba de donde termina la barra de tareas de windows (Captura 1) y a veces abajo (Captura 2)

![image](https://cloud.githubusercontent.com/assets/7788073/3168996/2a4484d8-eb90-11e3-9013-6264dd6c3fab.png)

![image](https://cloud.githubusercontent.com/assets/7788073/3168997/3b2792ea-eb90-11e3-8342-5004d3afff90.png)

**Comment by albarra** [comment]
Me pasa lo mismo. Es un comportamiento esperado?

**Comment by renraw** [comment]
me pasa lo mismo, he intentado reinstalar y sigue igual, solo pasa en modo fullscreen

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by renraw** [comment]
gracias
