### ISSUE TITLE
Sin audio, video con problemas

### ISSUE THREAD

**Issue by juanvisbal** [Cuevana/storm#102]
He estado teniendo un problema con la aplicación. No carga el audio y el video carga con pausas pequeñas cada minuto. No puedo ver nada, realmente.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by ElRauloCasla** [comment]
Hola, cargo por medio del magnet de la app este torrent y no sale el sonido. lo mismo me pasa con tranformers 4. Las torren son de KicKass. 

Edge of Tomorrow 2014 1080p WEB-DL DD5 1 H264-RARBG

Transformers.Age.of.Extinction.2014.1080p.WEB-DL.DD5.1.H264-RARBG

En el caso de Tranformes tampoco me deja elegir los sub mas alla de que el torren viene con 5 idiomas de sub. Tengo la ultima versión de la app. Alguna solución?
gracias.
Raul.

**Comment by Cuevana** [comment]
Eso es porque algunos videos tienen codecs no compatibles con las versiones compiladas de ffmpeg que incluye la aplicación. Por ej, algunos videos usan el codec HE-AAC, pero por el momento la versión compilada sólo soporta AAC.

**Comment by lusinqui** [comment]
Saludos, eh Descargado la aplicación y ningún video se escucha. por el momento.
