### ISSUE TITLE
Problemas en general

### ISSUE THREAD

**Issue by Rionoh** [Cuevana/storm#103]
Estos son los problemas que encontré yo en la app y que muchos ya son tema conocido.

1 - Los subtitulos aparecen con Simbolos de interrogación, reemplaza letras por símbolos de interrogación.

2 - Paras la película por 10 minutos y cuando pones play devuelta la vuelve a iniciar desde 0.

3 - A veces se tilda la pelicula y pones play y tambien la vuelve a iniciar desde 0

4 - La barra de abajo donde esta la duración de la película, para pararla o darle play, el globito de los subtitulos y demas, cuando sacas el cursor del mouse para ver la pelicula, la barra esa desaparece y aparece constantemente no se ""minimiza", va y vuelve durante toda la película cada 1 minuto y sin tocar el mouse. Sale para arriba y vuelve a esconderse así constantemente.

5 - El cursor del mouse si lo dejas en el medio de la pantalla o alrededor no desaparece, tenes que "tirarlo" hacia izquierda o derecha.

6- La aplicación tarda en abrir y a veces se tilda.

7 - Estaría bueno que la ventana del programa se pueda minimizar a un costado en "iconos ocultos" y que quede sola abierta la pantalla de la pelicula. Por que si cerras la ventana del programa se cierra la ventana de la pelicula.

Espero que puedan corregir estos errores! Muchas gracias! muy buena la pagina / aplicacion sigan asi.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
