### ISSUE TITLE
Películas offline?

### ISSUE THREAD

**Issue by hazi98** [Cuevana/storm#104]
Hola, me encanta su programa, y eso de las películas por torrent es una maravilla, pero me he dado cuenta que se almacenan en un folder dentro de AppData/Local/Temp y he visto que se almacena en varios archivos, pero si quiero abrirlos, sólo puedo abrir el primero de todos como video, pero aunque el reproductor marque la duración total de la película, sólo se muestra una parte de esta, y si trato de abrir los otros archivos me da error.
¿Hay alguna manera de juntar todos estos archivos en un solo video?

**Comment by Cuevana** [comment]
Es posible, pero no de manera simple desde el explorador de archivos. Se debería generar una herramienta para obtener los archivos unidos en uno. Lamentablemente esto no es prioritario por el momento, pero si te interesa puedes investigar cómo hacerlo viendo como hace el modulo que usa Storm para ello: https://github.com/mafintosh/torrent-stream
