### ISSUE TITLE
La app es muy inestable...

### ISSUE THREAD

**Issue by mavnono** [Cuevana/storm#107]
Buenas primero que nada queria felicitarlos, disfrute mucho de la pagina web de cuevana y creo que esta app es un paso adelante y puede llegar a ser muy como da, no obstante y sabiendo que es una version beta solo queria hacerles saber que es terriblemente inestable, la mayoria de las veces es casi imposible ver una pelicula sin que a los 20 minutos arranque sola de nuevo, o nunca cargue, o quede loopeando en los primeros 20 segundos o cosas por el estilo, mas alla de los subtitulos y los servidores, creo yo, es mi humilde opinion, que deverian corregir estos problemas por que hacen muy poco funcional a la aplicacion, hasta ahora lo unico que pude ver bien fue un capitulo de la serie vikings despues de haber esperado una hora y de que se reiniciara incontables veces mientras acusaba una velocidad de descarga de 1,5 mbs :S pero bueno les tengo fe muchachos y se que pronto andara un poco mejor, desde ya infinitas gracias :D EXITOS!

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
