### ISSUE TITLE
Problemas con subtítulos y una sugerencia

### ISSUE THREAD

**Issue by pinochodel87** [Cuevana/storm#108]
Los subtitulos a veces no cargan, otras veces las tildes, las eñes y otros caracteres típicos del español aparecen reemplazados por un signo de interrogación en un rombo.

Sugerencia: hacer que el puntero del mouse se esconda automáticamente para OSX en mac.

**Comment by Cuevana** [comment]
Esto debería estar solucionado. Disculpen, costó más de lo que imaginábamos. Puede que tarde en actualizarse los cambios para algunos, pero en las próximas horas debería estar resuelto por completo.
