### ISSUE TITLE
Visualizador en Negro

### ISSUE THREAD

**Issue by r3ds1gn** [Cuevana/storm#109]
pues.. yo me eh bajado la app directamente de la pagina de cuevana, no tengo conocimiento compilandolo ni nada de eso, pasa que el app me corre perfecto, pero cuando selecciono alguna pelicula, me aparece cargando los torrents (carga perfectamente) luego se abre la pantalla del reproductor, los botones aparecen correctamente, (play, subtitulos, fullscreen, sonido, tiempo) pero el reproductor solo se queda en negro y nunca cambia, no se escucha sonido alguno, y el timming de la pelicula esta estable en 0:00:00 - 0:00:00, tengo entendido que es algo de ffmpefsumo.dll pero no encuentro la manera de "cambiarlo" ya que en mi carpeta donde tengo instalado cuevana storm solo trae la aplicacion, 4*dll's, un archivo pak, un archivo dat y por ultimo el uninstall, uno de los dll's es el ffmpegsumo, me eh bajado el que tienen aqui para win  (uso windows 7) lo cambio por el otro (borro el otro, luego lo pego en la carpeta) pero cuando abro de nuevo el app y pongo a reproducir una pelicula, el error persiste, eh intentado tambien abrir la app como administrador, mas no hace ningun cambio, podria alguien ayudarme?
 se los agradeceria mucho!!!

**Comment by Mato2014** [comment]
Tengo el mismo problema. Soluciones?? Gracias

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by guarro** [comment]
sigue sin funcionar en windows 7, una pena.

**Comment by Cuevana** [comment]
Lo hemos probado en win 7 y funciona. Por favor envia más detalles de tu OS y PC para buscar la fuente del problema.

**Comment by guarro** [comment]
En windows 8.1 de 32 bits si me funciona, pero en  Windows 7 ultimate, 32 bits, service pack 1 nunca pude hacerlo funcionar. La pc tiene los mismos drivers y codecs en los sistemas operativos.

**Comment by Cuevana** [comment]
@guarro estamos hablando de la versión ejectuable de la app o corriendo `npm start` desde el repositorio?

**Comment by guarro** [comment]
De la versión ejecutable, conseguí hacerla funcionar ejecutándola con compatibilidad windows XP, asi que si en windows 7 no les funciona prueben hacerlo asi. Muchas gracias por tratar de solucionar los problemas a los usuarios y de mejorar el programa día a día. Saludos.

**Comment by Cuevana** [comment]
El usuario @olivercs parece haber encontrado el problema. Ya actualizamos el repositorio con su aporte. Esperamos tener una versión empaquetada pronto también.

**Comment by caparkove** [comment]
Sigo teniendo el mismo problema. No sé nada acerca de programación. Ayuda.

**Comment by alebel07** [comment]
Hola! Bajé cuevana storm de la página oficial y lo instalé sin problemas. Puedo abrirlo y ver las opciones, pero no veo ninguna película ni serie, ni nada. Es como si estuviera vacío. 
El visualizador de contenido aparece siempre negro. Pareciera que no accedo a la base de datos o algo así. Uso Windows XP y supongo que me falta algún complemento o algo. ¿Podrían ayudarme con este tema? MUCHAS GRACIAS!!!
