### ISSUE TITLE
La aplicacion no se ejecuta

### ISSUE THREAD

**Issue by lancbans** [Cuevana/storm#111]
Tengo un problema con la aplicacion, y es precisamente el que esta en el titulo: la apliacion no se ejecuta, cuando trato de abrirla me aparece en la barra de tareas pero no me abre ninguna ventana, esto empezó a pasar derrepente ya que antes si podia pero ultimamente esta fallando en eso, ya trate de desinstalarla e instalarla de nuevo, y nada sigue igual, estoy usando windows 8 y ese no es el problema ya que como mencione anteriormente, si podia días atras ejecutarla, que puedo hacer para que vuelva a funcionar?

**Comment by juankaeq** [comment]
Viejo metete al administrador de tareas (ctrl+shift+esc), y busca la tarea de cuevana, expandí el menu para que te salga el sub-proceso de cuevana. Hacele click derecho y undís maximizar y te va a salir de nuevo la aplicación.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
