### ISSUE TITLE
Los subtiulos no terminan de cargar

### ISSUE THREAD

**Issue by joellembert** [Cuevana/storm#112]
Hola, 
cuando intento cargar los subtitulos se quedan loading y no pasa nada.

**Comment by jlmaglione** [comment]
Hola confirmo que sigue pasando. Ha pesar que este tema se haya cerrado en otra entrada.
Por ejemplo: Serie Orphan Black.Temporada 2 Episodio 6.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
