### ISSUE TITLE
Películas sin subtítulos

### ISSUE THREAD

**Issue by juanmacio** [Cuevana/storm#114]
"Ace Ventura: Pet Detective" (1993) no tiene subtítulos en 720p ni 1080p.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by juanmacio** [comment]
Lo que comento acá no es un problema de la app sino casos concretos que persisten hasta en la nueva versión.

"Ace Ventura: Pet Detective" (1993) y "Meet The Parents" (2000) no tienen subtitulos.
