### ISSUE TITLE
Cuevana Storm blocks other internet traffic

### ISSUE THREAD

**Issue by Elijen** [Cuevana/storm#115]
It seems like the app uses the whole bandwidth even when downloading/uploading is not on max speed. When I play a movie I cannot access any website using my browser. The problem usually persists even after closing the movie and disappears after the whole app is closed.

Strangely iMessage seems to work without problems. Could be something with DNS as browser blocks on "Resolving host".

Some info:
Cuevana Version 0.1 Beta (0.1b)
OS X Mavericks 10.9.4
Macbook Pro 13-inch, Mid 2012
100Mbit internet, router connected via ethernet cable

**Comment by Cuevana** [comment]
We launched a new version of the app, this issue should be fixed. Thank you.
