### ISSUE TITLE
Archivos temporales.

### ISSUE THREAD

**Issue by Azuleo** [Cuevana/storm#118]
Me gustaria saber si hay alguna forma de cambiar el directorio temporal que la aplicacion usa por defecto en windows 7 ya que no tengo demasiado espacio en la unidad donde esta actualmente.
Saludos!

**Comment by Cuevana** [comment]
Es posible, pero por el momento no es prioritario lamentablemente. Si quieres hacer un PR que brinde una solución a esto genial.

**Comment by Cuevana** [comment]
Cerrando, duplicado de #113.
