### ISSUE TITLE
A serie que esta en el sistema no se puede acceder salvo desde historial

### ISSUE THREAD

**Issue by Marilumorand** [Cuevana/storm#119]
A la serie Fargo pude acceder desde nuevos episodios hace un tiempo atras.  Ahora que no esta mas en nuevos episodios yo puedo acceder desde historial porque ya habia accedido antes.  No aparece en ninguna lista ni en ninguna busqueda, ni por titulo, actor o ningun otro parametro.  Para un nuevo usuario no hay forma de acceder.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
