### ISSUE TITLE
series en 720p?

### ISSUE THREAD

**Issue by sharkiller** [Cuevana/storm#12]
solo en 360p me parece espantoso. por lo menos 480p pero definitivamente lo mejor seria 720p.
es un problema con los torrents? o es una base de datos con torrent custom? estaria bueno una api donde se pongan los torrent 720p y 480p oficiales y proper de cualquier pagina y automaticamente detecte el que mas ratio tenga.
la posibilidad de elegir un torrent custom seria perfecto, lo mismo para los subtitulos que lo vi en un pull request.

**Comment by ivantodorovich** [comment]
Sobre las series en 720, supongo que depende del API de Cuevana. Debería ser incorporado ahí. Mi conexión lamentablemente no alcanzaría a streamearlo.. :'( pero me parece algo importante para muchos.

Por la reproducción de torrents custom la verdad que no sería muy dificil de hacer, y a mi personalmente me encantaría verlo implementado, pero tal vez se aleje de la finalidad del app. Tendríamos que ver qué dice @Cuevana.

**Comment by sharkiller** [comment]
si la finalidad de la app va a ser mirar series en 360p no le veo nada de futuro.

**Comment by ivantodorovich** [comment]
@sharkiller edité mi comentario, no me expresé bien :dancers:

**Comment by mama21mama** [comment]
La tv usa menos de 360, nadie se queja y paga la tv por cable.

**Comment by ivantodorovich** [comment]
@mama21mama no me parece que @sharkiller se esté quejando. Es una sugerencia válida. Además existen torrents en 720p de prácticamente todas las series, y en la mayoría de los casos los subtitulos coinciden. Es cuestión de incorporarlos nada más.

**Comment by Cuevana** [comment]
Actualmente la app no muestra series en 720p debido a que están encodeadas con otros codecs. Las versiones actuales de ffmpeg compiladas con Chrome no reproducen el audio de las versiones 720p de las series. Con el video no hay problemas, es h.264, aparentemente el audio es otra variante de AAC no soportada.
Una posible solución sería compilar otras versiones de ffmpeg con el codec necesario (hace falta un research más extenso).

**Comment by fluzzi** [comment]
por lo que vi, los mkv tienen AC3 que es licensiado y pro eso no lo esta en ffmpeg, habría que compilar un ffmpeg que lo pueda reproducir

**Comment by Cuevana** [comment]
Si podemos hacer funcionar la reproducción 720p sin problemas, agregamos soporte desde la API y se incluyen inmediatamente. Es cuestión de compilar ffmpeg con los codecs necesarios.

**Comment by sharkiller** [comment]
lo que hay que compilar seria el ffmpegsumo qeu usa chromium. son muchos gigas de codigo y muchas horas de compilacion. ya veo porque nadie lo compilo hasta ahora. mas uqe nada porque se necesitan para los diferentes OS. estaria bueno podes usar el track de sonido de los 360p en los 720p, pero me imagino que aparte de imposible debe ser problemas para la sincronizacion y demas. total el 360p no gasta nada de conexion.

**Comment by fluzzi** [comment]
Che y arrancar los videos en vlc o meter otro plugin de video que si funcione? no es la mejor solución pero podriamos ver series en hd

**Comment by ivantodorovich** [comment]
Arrancar en VLC o un reproductor definido por el usuario sería posible. De hecho así funciona `peerflix`. Es algo que en algún momento se me cruzó por la mente, para agregar bajo preferencias avanzadas.

**Comment by fluzzi** [comment]
Claro se que es posible y estaba viendo de armar algo pero queria ver que pensaban, quizás forzar que si es series en hd, reproduzca en vlc o una opción cuando le damos play

**Comment by guidocelada** [comment]
Lo de reproducir en vlc es un parche temporal me parece a mi. Lo ideal es que esté todo integrado en la app.

**Comment by ivantodorovich** [comment]
Si, eso está claro, hay que compilar el ffmpegsumo para eso..

Igualmente está bueno que el usuario pueda elegir otro player, más allá de
que hoy sea la única forma de reproducir este contenido.

**Comment by Cuevana** [comment]
Este request/feature es prioritario ahora para nosotros. Estamos analizando distintas opciones para solucionarlo. Cualquier sugerencia/ayuda es bienvenida.

La más limpia sería compilar ffmpegsumo sin dudas. Pero hay que hacerlo para cada OS y arquitectura, lo cual puede no ser tan fácil.

La otra sería utilizar modulos como https://github.com/fluent-ffmpeg/node-fluent-ffmpeg o https://github.com/trenskow/stream-transcoder.js para hacer un transcoding en tiempo real. Obviamente esta solución tiene un overhead y por ende mayor consumo de CPU.

**Comment by cabrote** [comment]
Opino lo mismo cualquier material deberia estar minimo en 720p. Espero encuentren una solucion...
