### ISSUE TITLE
Barra de busqueda crashea con ciertas busquedas

### ISSUE THREAD

**Issue by FerPerales** [Cuevana/storm#120]
Hola!
Encontré un bug en la version de Mac (desconozco si es exclusivo de este sistema operativo)

La app crashea con ciertas busquedas. Una que pude identificar (y que deberia servir para reproducir el bug) es buscando 'int' 

Anexo link a video con otra busqueda que tambien provocó que la aplicacion crashera

http://recordit.co/MbNAOjMQNY

Espero poder revisar el codigo fuente el fin de semana y enviar un PR o al menos anexar mas informacion en este issue

Saludos!

**Comment by Cuevana** [comment]
@FerPerales Gracias por el report. Estamos enterados.
En estos meses estuvimos trabajando en un refactoring de la app desde cero que soluciona este problema y muchos más. Estamos terminando de preparar un build de esta nueva versión y la publicaremos en el corto plazo (probablemente la semana que viene).

Saludos!

**Comment by dsdcdev** [comment]
Pasa lo mismo el Win 7.

Saludos !

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
