### ISSUE TITLE
Browser issue

### ISSUE THREAD

**Issue by jorgegeplaza10** [Cuevana/storm#121]
cuevana storm browser isnt working it says uncaught node .js error when im trying to look for the exorcist when i type the o it pops up the error

**Comment by Draxler** [comment]
Win7

---

Confirm this issue. After start writting search term into search box, i'm getting ''uncaught node .js error'' ... Before everything was ok but now out of nowhere these error messages start to reapear everytime search box is used ...

**Comment by Cuevana** [comment]
We launched a new version of the app, this issue should be fixed. Thank you.
