### ISSUE TITLE
No puedo cargar el video .. nisiquiera empieza a cargarse

### ISSUE THREAD

**Issue by seattle98** [Cuevana/storm#123]
no puedo ver ninguna película o serie ya que no se carga la barra que parece cuando le doy clic a reproducir, lo deje para ver si con el tiempo comenzaba a cargar pasaron 30minutos y nada ..intente con diferentes películas, cambiando la resolución y ya por ultimo desinstalé la App , reinicie la pc y la reinstale ni con eso funciono. AYUDA

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
