### ISSUE TITLE
No puedo mover la ventana de la app

### ISSUE THREAD

**Issue by vetom** [Cuevana/storm#127]
Hola, lo primero es felicitarles, excelente trabajo!

Estoy usando OS X 10.9.4, tras utilizar la app con el Apple TV (escritorio extendido), cuando la desconecté la aplicación se quedó ocultando la parte superior fuera de la pantalla, incluyendo barra de búsqueda y demás, por lo que no pude alcanzar la barra superior y moverla de lugar.

Al final pude resolver el problema conectando la computadora a un monitor externo y aumentando su resolución.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
