### ISSUE TITLE
PROBLEMAS 

### ISSUE THREAD

**Issue by kike13** [Cuevana/storm#129]
Uncaught node.js Error
typeerror: Cannot read property 'length' of undefined    at t.renderGrid (app://cuevana/js/main.js:533:83)    at callback (app://cuevana/js/main.js:486:7)    at Request.eval [as _callback](app://cuevana/js/main.js:508:6)    at Request.self.callback (C:\Users\Usuari\AppData\Local\Temp\nw5596_23773\node_modules\request\request.js:121:22)    at Request.EventEmitter.emit (events.js:98:17)    at Request.eval (C:\Users\Usuari\AppData\Local\Temp\nw5596_23773\node_modules\request\request.js:978:14)    at Request.EventEmitter.emit (events.js:117:20)    at IncomingMessage.eval (C:\Users\Usuari\AppData\Local\Temp\nw5596_23773\node_modules\request\request.js:929:12)    at IncomingMessage.EventEmitter.emit (events.js:117:20)    at eval (_stream_readable.js:920:16)

me sale al teclear solo 3 teclas en el buscador 
SI PUDIERAN SOLUCIONARLO SERÍA PERFECTO GRACIAS

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
