### ISSUE TITLE
Bug: confirmacion al cerrar video tiene el estilo roto

### ISSUE THREAD

**Issue by sharkiller** [Cuevana/storm#13]
![image](https://cloud.githubusercontent.com/assets/712193/2597752/fe891fe6-bab8-11e3-898f-71ab41ed8696.png)
 probe reiniciando el programa y en distintas peliculas.

**Comment by ivantodorovich** [comment]
Parece ser un error de NodeWebkit en Windows cuando el "Aero" está desactivado..

No sabría cómo solucionarlo sin dejar de utilizar el MsgBox incorporado. Habría que reemplazarlo por una confirmación hecha en HTML, dentro de la ventana del player (lo mas fácil) o invocar otra ventana de webkit sólo para eso.. y sino directamente no pedir confirmación.

**Comment by Cuevana** [comment]
Por ahora hemos desactivado este alerta. Estaremos pendientes de los avances de este bug visual en node-webkit.
