### ISSUE TITLE
problemas con la aplicacion 

### ISSUE THREAD

**Issue by nicoce** [Cuevana/storm#131]
tengo un pequeño erro con la aplicacion... desconozco si soy el unico en tenerlo pero la aplicacion se traba cada 3 o 5 segundos. Logro ver las peliculas si dejo la aplicacion abierta durante una hora y solamente abro la ventana de la pelicula, si no regresa el problema.

**Comment by nicoce** [comment]
error*

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
