### ISSUE TITLE
Someone with 32bit linux?

### ISSUE THREAD

**Issue by Cuevana** [Cuevana/storm#132]
We need to get the `libffmpegsumo.so` that comes with Chrome 36.0.1985.143 to build for the 32 bit systems with correct codec support.
Anyone with a linux 32-bit system that can get that and make a PR?
Thank you

**Comment by lucianolev** [comment]
Done :) https://github.com/Cuevana/storm/pull/141

**Comment by Cuevana** [comment]
Great! Thanks!
