### ISSUE TITLE
English Support

### ISSUE THREAD

**Issue by pepijn809** [Cuevana/storm#138]
I saw some additions in the code for english support. Still could not find it in the release from the cuevana.tv

Is that gonna be added soon?

Thanks!

**Comment by Draxler** [comment]
Pepijn :+1:   

---

I wonder the same thing; (when will English version become available ...)

**Comment by Cuevana** [comment]
Fixed afc8d3f02e67e0c23da150e1056754a2bde62012. Was missing locales directory that needed to be shipped in windows/linux version. Expect a packaged version soon.

**Comment by Draxler** [comment]
Any chance for Storm **Build** (English) get posted, if relese is not yet ready ?
