### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by fluzzi** [Cuevana/storm#139]
desde la nueva version me es imposible usar el npm install, esta usando algo más que nodejs ahora?

gracias!

**Comment by Cuevana** [comment]
Devuelve algún error? Probamos clonando el repositorio desde cero y luego ejecutando `npm install` y todo se instaló bien.

**Comment by fluzzi** [comment]
este es el error que meda al intentar instalar

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\windows\system32>cd C:\Users\federico.lucas.luzzi\Desktop\cuevanastorm

C:\Users\federico.lucas.luzzi\Desktop\cuevanastorm>npm install
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/Cuevana/torrent-health) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/Cuevana/torrent-health) undefined
npm ERR! git clone https://github.com/Cuevana/torrent-health undefined
npm ERR! git clone https://github.com/Cuevana/torrent-health undefined
npm WARN deprecated gulp-clean@0.3.1: use gulp-rimraf instead
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\Users\federico.lucas.luzzi\Desktop\cuevanastorm
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ENOGIT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\federico.lucas.luzzi\Desktop\cuevanastorm\npm-debug.log
npm ERR! not ok code 0

C:\Users\federico.lucas.luzzi\Desktop\
