### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ivantodorovich** [Cuevana/storm#14]
I think localization should be considered. 

We can use JSON files to store localization strings, and use some kind of sprintf translation function in in every string. I'm sure there are JS libraries that can handle this properly.

For localized synopsis we might need to extend Cuevana api, or make use of a external metadata service. I don't know how Cuevana API works, if it already queries and caches synopsis from a service, shouldn't be hard to extend it.

**Comment by ivantodorovich** [comment]
Related issues https://github.com/Cuevana/storm/issues/4 https://github.com/Cuevana/storm/issues/9

**Comment by Cuevana** [comment]
We are open to localization. We didn't went for this in first beta, but is something to consider.

**Comment by Cuevana** [comment]
Done. a02cddc99d6ab71829ce2d67ad3e274746f9f45a
