### ISSUE TITLE
Peliculas se traban

### ISSUE THREAD

**Issue by MauriFont** [Cuevana/storm#142]
Cada pelicula que quiero ver se va trabando de a poco, ya sea en 720p o 1080p. La velocidad de descarga es muy alta y siempre veo peliculas con esas definiciones sin ningun problema por lo que pienso que puede ser un problema del programa.

**Comment by Cuevana** [comment]
Realizamos optimizaciones para mejorar considerablemente la performance. La última versión ya mejora esto. Aún no la empaquetamos para descarga desde el sitio, pero lo haremos en las próximas horas.
