### ISSUE TITLE
FPS muy bajos

### ISSUE THREAD

**Issue by santigarcor** [Cuevana/storm#149]
El problema esta en que al reproducir la película los fps son muy bajo y la película reproduce pero con mucho lag, esto me sucede en ubuntu y no es solo en mi pc ya he probado en varios pc ubuntu y el problema es el mismo

**Comment by juancentro** [comment]
Tengo el mismo problema en Ubuntu 14.04

**Comment by idiazu** [comment]
Lo mismo acá, en Ubuntu 14.04. Mi computador tiene una Nvidia Optimus y probé con ambas tarjetas gráficas y no hay ninguna diferencia.

**Comment by cabrote** [comment]
Lo mismo en Windows 7 Dual Core Geforce GT520. Es la unica app que me freezea los videos.

**Comment by santigarcor** [comment]
Sigue sin solución, yo tengo Ubuntu 14.04, la versión anterior me funcionaba sin problemas y al cambiar a esta última versión se laggea o freezea como quieran llamarlo

**Comment by qievenz** [comment]
Me pasa lo mismo.. nadie tiene una solución temporaria al menos?
