### ISSUE TITLE
Add Report button

### ISSUE THREAD

**Issue by ivantodorovich** [Cuevana/storm#15]
Some episodes have desynchronized subtitles, or missing ones. Might also have video/audio problems, dead torrents. etc. It would be useful to have a way to report these things.

It may even detect when a sub or video have multiple reports from different people, and automatically display a warning, or even remove it.

**Comment by Cuevana** [comment]
This is something to consider for a future release.

**Comment by Foxito** [comment]
A mi tambien me parece necesario esto, tambien encontre algunos episodios que estaban bajos de seeds y resultaba dificil verlos. Mas teniendo en cuenta el problema que ocurre al pausar los videos.
