### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by fearslayer** [Cuevana/storm#2]
Hello, how do i build this package? i have installed gulp and all dependencies but i cannot build it, i dont know if i did it right but it gives me this error:

Error caught from uglify: Unexpected token operator «-», expected punc «:» in C:\storm-master\assets\js\vendor\lib.js. Returning unminifed code

**Comment by Cuevana** [comment]
Have you changed or edited any files in assets/js?
We don't get that error, does it specify any specific line for the "Unexpected token operator" error?

**Comment by fearslayer** [comment]
not line, it shows the file only, lib.js and its not on vendor folder :(

**Comment by ivantodorovich** [comment]
I didn't have the same error, but I found some missing package.json dependencies. Once, I had no more js errors.

Now I'm struggling with the player, who doesn't seem to play videos. I just get a black screen and 00:00  00:00 playback time. No js errors. Sounds like a codec error with my node-webkit.

Have you rebuild a node-webkit binaries with a different codec support?

**Comment by Cuevana** [comment]
Ivan could you reference the missing package.json dependencies?

To play videos you need the ffmpegsumo.so or ffmpegsumo.dll (win). Just get the latest packaged with Google Chrome.
https://github.com/rogerwang/node-webkit/wiki/Support-mp3-and-h264-in-video-and-audio-tag

**Comment by Cuevana** [comment]
We have included ffmpegsumo files and referenced instructions in the link to build the app.

**Comment by ivantodorovich** [comment]
Excellent, got it working with the link you provided. Thanks!

**Comment by fearslayer** [comment]
how do you guys are packing it?

edit:

Got it to work :smile: 

one question, the cuevana api(http://api.cuevana.tv) support other langs  ? it would be cool if we can add custom subs or use the api to search them

**Comment by uilson** [comment]
Hi, i'm having some problems with the build and running the files, can anyone help me to run the files?
When I open the nw.exe it loads the index.html, but it wont load the styles or anything else, it just shows the html.

A tutorial would be great (by the way, i'm using node-webkit for the 1º time).

Thank you to all those o can help me.

**Comment by Marambelo** [comment]
hi, what version of node webkit do you use?

**Comment by uilson** [comment]
hi, I'm using the v0.9.2 for windows.

**Comment by ivantodorovich** [comment]
@uilson I had problems with v0.9.2. Not the ones you describe, though.

I'll suggest you to try with NodeWebkit 0.8.5.

**Comment by zombiezoom** [comment]
Guys, I am not expert in building apps from source and I did my best (searching on google) trying to figure out what to do. I installed the dependencies via "npm install" and run the command "gulp" but I don't know what's next? could someone please give me some directions? thank you in advance

**Comment by ivantodorovich** [comment]
Download nodewebkit 0.8.5 and run the project folder with it

**Comment by sharkiller** [comment]
how to build and run from shell in the storm repo
- install dependencies

```
npm install
npm install nodewebkit@0.9.2-2
npm install gulp@3.5.6
```
- compile **(optional, not recommended for testers)**

```
.\node_modeules\.bin\gulp
```
- copy from this repo the ffmpegsumo that match your system into

```
\node_modules\nodewebkit\nodewebkit\
```
- run

```
.\node_modules\nodewebkit\nodewebkit\nw \ --debug
```

**Comment by uilson** [comment]
Let me know if I understand correctly @sharkiller , I download zip of the repo extract the repo to a folder (in this case a folder named storm-master in the disc C: ), then I open the 'Node.js command prompt' and do the 'cd c:\storm-master' right?

then I do your steps (still inside of the c:\storm-master folder):

install dependencies

```
npm install
npm install nodewebkit@0.8.5
npm install gulp@3.5.6
```

build

```
.\node_modeules\.bin\gulp
```

run

```
.\node_modules\.bin\nodewebkit
```

and this should run the Cuevana storm right?

Except it doesn't, it open the nodewebkit "browser" and shows a message:

```
Invalid package 
There is no 'package.json' in the package, please make sure the 'package.json' is in the root of the package.
```

**Comment by zombiezoom** [comment]
@ivantodorovich @sharkiller  Thanks a lot guys. It works fine now :D

**Comment by sharkiller** [comment]
@uilson modify your package.json and in version line at the top use "0.2.0" that cause a broken package.json. and do all the step again to install the new dependencies.

ps: remember to copy the ffmpegsumo.dll or .so to the nodewebkit build. `storm\node_modules\nodewebkit\nodewebkit` 
also add --debug parameter to the nodewekit CLI command to activate the developer console.

**Comment by uilson** [comment]
thank you @sharkiller, it looks like it is running ok, at least it opens the cuevana storm and I can select the movies/series.

By the way do you know why it won't run with the "0.1.0" version?

Thank you once again.

**Comment by ivantodorovich** [comment]
Since https://github.com/Cuevana/storm/commit/1623f03e85c8698b9dff7e0dcc72eced7e271a58, at least on windows, the `ffmpegsumo.dll` packed in the `ffmpegsumo/win/` is built for `nodewebkit@0.9.2`

Don't know about other platforms, can someone confirm?

**Comment by sharkiller** [comment]
Desde los cambios de hoy se me queda trabado en "Cargando torrent...". Cosa que no pasa en el build oficial, probe con los dos nodewebkit y lo mismo. Con el 0.9.2 a la larga conecta y se ve, con 0.8.5 pasa un tiempo y me tira error de que no se pudo leer el torrent o algo asi.
Mire problemas de permisos en carpetas, el firewall, el antivirus y nada. Ayer andaba perfectamente. Sera problemas de ahora o será justo casualidad?

**Comment by ivantodorovich** [comment]
@sharkiller A mi me anda bien.. recién termine de ver una serie justo. Win7 y `nodewebkit@0.9.2`.
No será que justo el torrent que querés abrir tiene pocos seeds?

**Comment by sharkiller** [comment]
@ivantodorovich nono, probe varios torrents de varias peliculas y series. como por ejemplo el ultimo capitulo de walking dead o peliculas que tienen muchisimos seeders y nada. Lo raro es que tengo instalada la version oficial y ahi si anda bien. El problema es que ni llega a la parte en la que conecta con los seeders porque no llega nunca a terminar de cargar el torrent, 
Win7 y nodewebkit@0.9.2 y 0.8.5
por cierto usando nodewebkit@0.9.2 no se me activa las dev tools cosa que con la version 0.8.5 si.

**Comment by ivantodorovich** [comment]
@sharkiller el hecho que no se activen las devtools puede ser indicio de alguna excepción no atrapada.

Lo raro es que acá anda bien.. veo como cargan los seeds y despues de unos segundos arranca la reproducción. 

Proba hacerle un reset al repo, no sea cosa que te haya quedado algún archivo en conflicto y este causando errores!

**Comment by sharkiller** [comment]
@ivantodorovich lo tengo con el programita de git que te detecta cualquier cambio solo, pero de hecho hoy mismo hice un reset cuando me desperte por eso me extraña. voy a borrar la carpeta node_modules e instalar todo de neuvo

edit1:Bueno borre todo, volvi a instalar todo de 0 fresco y sigue el mismo problema. Se clava en cargando torrent y sigue sin aparecer las dev tools con 0.9.2
Fuera de eso la app anda bien, no noto nada fuera de lo normal salvo que falla al cargar los torrents.

**Comment by sharkiller** [comment]
@ivantodorovich mmm si le pongo true a isDebug anda, y si pongo que me muestre los parametros en la consola me da una array de 0 y le estoy dando el parámetro --debug.
Me podes decir el comando que usas vos para ejecutar la aplicacion?

**Comment by ivantodorovich** [comment]
`nw.exe storm/ --debug`

**Comment by sharkiller** [comment]
bueno al fin pude hacer que ande "estable".
![image](https://cloud.githubusercontent.com/assets/712193/2624050/36cfe4ec-bd1c-11e3-9ac6-fa4e0b93f248.png)
 Ahora si me toma bien los parametros pero la carga de los torrent sigue siendo muy errática, algunos tardan 15 segundos en cargar el torrent y otros hasta 1 o 2 minutos.

Y vuelvo a decir, tarda en cargar el torrent, no los seed, es como que falla a leer el .torrent o tiene problemas al bajarlo. el antivirus/firewall desactivado por las dudas. la verdad que no se que puede ser ya que el oficial publico me anda perfectamente. offffffff

**Comment by vhanla** [comment]
Lo probé en Mavericks, utilicé nodewebkit 0.9.2 y también 0.8.5, copié ffmpegsumo.so como indican, la carga del torrent demora un poco pero lo logra en ambas versiones, sin embargo el reproductor sólo muestra una pantalla negra con el medidor de velocidad de descarga.

Lo curioso es que al cerrar el programa la conexión de internet se va, en realidad el DNSresponder ya no responde, y tengo que matar el proceso y esperar hasta que responda otra vez, de lo contrario me quedo sin acceso a internet.

**Comment by guidocelada** [comment]
me pasa lo mismo que @vhanla

**Comment by sharkiller** [comment]
estan seguros que copiaron el ffmpegsumo en el lugar correcto?
cada vez que se instala el nodewebkit sobreescribe el ffmpegsumo

**Comment by guidocelada** [comment]
lo copié a ./storm/node_modules/nodewebkit/nodewebkit/

**Comment by sharkiller** [comment]
y como lo ejecutan?

```
.\node_modules\nodewebkit\nodewebkit\node-webkit.app \ --debug
```

?

**Comment by guidocelada** [comment]
primero hice 

```
alias nw="/Applications/node-webkit-old.app/Contents/MacOS/node-webkit"
```

y despues, parado en ./storm/

```
nw "./" --debug
```

(probe con las dos versiones 0.9.2 y 0.8.5)

**Comment by ivantodorovich** [comment]
@guidocelada pero estas copiando la libreria al nodewebkit que está en `./storm/node_modules/nodewebkit/nodewebkit/` y después estás ejecutándo éste otro: `/Applications/node-webkit-old.app/Contents/MacOS/node-webkit`.

Decidite por uno y poné la librería ahí!

**Comment by guidocelada** [comment]
ah bien ya me queda mas claro. pasa que en esa carpeta no tenia el node-webkit. de hecho ni existía. pensé que estaba hardcodeada la ruta esa de alguna manera. ahora lo pruebo y aviso.

EDIT: ya me anda bien. Copie el ffmpegsumo a su correspondiente lugar en en /Applications/ ....

**Comment by ivantodorovich** [comment]
:+1:
