### ISSUE TITLE
API cerrada, el fin de cuevana.

### ISSUE THREAD

**Issue by bet0x** [Cuevana/storm#205]
Escribo esto para resumir algo que comente hace mucho tiempo en un bug request. Cuevana usa un api cerrada y por ende ahora que ellos no reciben "donaciones" no actualizan ni películas ni serie. Se dan cuenta de cual es el negocio cierto?.

Si esto es un cliente de torren mas avanzado se podrían usar mil opciones las cuales permitirían tener un sistema descentralizado del mismo api pero quisieron cerrarlo por que así podrían hacer negocio.

Voy a forkear esto y arreglar dicho problema. Me avisan si alguno se quiere sumar.

**Comment by danielr18** [comment]
Estoy contigo, aunque no tengo mucho conocimiento de Node.js ni de como funciona.

**Comment by bet0x** [comment]
Estoy pensando como armar una arquitectura de actualización descentralizada para esto, donde uno tenga feeds y luego se compartan automáticamente. Existen varios sitios con apis y demás.

Solo se debería generar un modulo para esto, remover los callados a api.cuevana.tv y listo.

**Comment by ghost** [comment]
Me uno a la causa en todo lo que pueda ayudar.

**Comment by victorgilalejandria** [comment]
Igual, me uno a lo que pueda, envíenme el URL del fork para tenerlo.

**Comment by jgab-net** [comment]
popcorntime

**Comment by LuisNara** [comment]
Hola bro, yo no soy programador, pero estoy en esto de las peliculas y contenido online hace tiempo, si tienen algún nuevo fork/proyecto puedo aportarles contenido, películas y series con varias semillas (Para que funcione el sistema).

Sí piensas montar algo nos avisas.

**Comment by Cu4rach4** [comment]
Se hizo algo? me gustaria participar!

**Comment by luisdevelop23** [comment]
avisan si tienen algo, para consumir su API,

**Comment by aurendev** [comment]
se logro hacer algo ?, soy programador, quiero colaborar
