### ISSUE TITLE
Error al pausar más de 3min

### ISSUE THREAD

**Issue by DarwinJ94** [Cuevana/storm#28]
Primero que nada felicitar por esta grandiosa app. Bien, he tenido dos problemas utilizando la app: Primero, al pausar cualquier tipo de contenido y dejarlo unos segundos/minutos y volver a reproducirlo para totalmente la película/serie y me obliga a volver a reproducir desde el principio la misma siendo esto un poco molesto. Segundo, deberían ocultar el puntero al estar en reproducción cualquier contenido y así evitamos tener que estar rodando el mismo fuera del marco de reproducción. Hasta ahora han sido esos los únicos dos problemas que he confrontado con la app.

**Comment by ivantodorovich** [comment]
Hola @DarwinJ94 !

No puedo replicar el primer bug.. se me pausa bien acá!

En cuanto al segundo, ahi mande un PR

**Comment by sharkiller** [comment]
El primer bug yo lo puedo confirmar ya que me paso varias veces. Al pausar y dejarlo por ejemplo 10' porque tenia que hacer algo, al volver reproduce correctamente unos segundos y después se activa el overlay de carga por siempre, si se la da play o pausa de nuevo empieza a cargar de 0.
Recuerdo que me paso al mirar Veronica Mars en 1080p para probar la app en mas de una vez.

Ahora me vino a la mente otro bug que no se si está presente todavia pero que me paso en la misma pelicula era que los primeros minutos de la barra de carga si querias hacer SEEK para cargar mas adelante, el primer medio centimetro de esa barra siempre marca como 0:00. No se si esta hecho aproposito como para hacer mas facil empezar la pelicula desde 0 pero me parece un fallo de diseño que no te permita elegir esos minutos. se podria agregar otro boton para eso al lado de play.

**Comment by ivantodorovich** [comment]
@sharkiller 

> Ahora me vino a la mente otro bug que no se si está presente todavia pero que me paso en la misma pelicula era que los primeros minutos de la barra de carga si querias hacer SEEK para cargar mas adelante, el primer medio centimetro de esa barra siempre marca como 0:00. No se si esta hecho aproposito como para hacer mas facil empezar la pelicula desde 0 pero me parece un fallo de diseño que no te permita elegir esos minutos. se podria agregar otro boton para eso al lado de play.

Creo que es porque sino fuera así, sería practicamente imposible volver al principio, debido a que se te va el cursor fuera de la ventana. Me pasaba con `video.js`. Tal vez se pueda "achicar" los pixeles que ocupa eso.. pero igualmente siempre podes usar las teclas IZQUIERA / DERECHA del teclado para hacer SEEK mas fino.

**Comment by sharkiller** [comment]
2 o 3mm es mas que suficiente como para tener lugar para empezar de 0. hay facil 10mm ahi.

**Comment by ivantodorovich** [comment]
@sharkiller 

Acá está el culpable:

```
// 5.1.mediaelement-and-player.js Line: 3232
newTime = (percentage <= 0.02) ? 0 : percentage * media.duration;
```

Menos de 2%, y redondea a 0. Es el source de mediaelement.

**Comment by DarwinJ94** [comment]
Sobre lo del bug de pausar el vídeo, me sucede casi siempre cuando lo dejo unos 3 minutos y vuelvo a retomarlo, se reproduce unos segundos y rápidamente se pone en negra la pantalla y para de reproducir. Uso Windows 8.1 por si sirve de algo.
![image](https://cloud.githubusercontent.com/assets/7192119/2623915/b3255c08-bd11-11e3-9e5c-9b958bcb7d1f.png)

**Comment by sharkiller** [comment]
@ivantodorovich no se le puede poner un porcentaje y un maximo? por ejemplo que quede el 0.02% pero que no sea mayor a 5px? o ponerle 2 o 3px fijos

@ivantodorovich @DarwinJ94 lo acabo de comprobar recien yo tmb mientras reinstalaba la repo, con el cliente oficial puse a reproducir una peli un rato y le puse pausa. cuando termino de instalar todo en la repo le doy play se vuelve la pantalla negra. Todo esto mientras el contador de seeds y velocidad funciona correctamente y bajando. si se le da pausa y play despues de esto la peli empieza de 0.

**Comment by ldolberg** [comment]
En Mac OS ya pude replicar varias veces el comportamiento. Luego de dejar en pausa algunos minutos no es posible continuar la reproduccion.

Version 0.1 Beta (0.1b) para Mac.

**Comment by sharkiller** [comment]
@ivantodorovich probaste el commit que hiciste para ocultar el cursor? con el ultimo build ahora noto que no se puede dejar el cursor sobre el reproductor porque ni bien se ejecuta el "hide" de los controles automaticamente vuelve a aparecer los controles y el cursor. asi todo el tiempo. Es como si tomará el ocultamiento del cursor como un movimiento del mismo por lo que lo hace activar de nuevo. La verdad no mire el codigo de esa parte.
No lo note antes porque como tengo 2 pantallas siempre dejo el mouse en el otro monitor.

**Comment by ivantodorovich** [comment]
Yo lo probé acá y funciona perfecto. De hecho no debería activar ningún
evento, lo único que hace es cambiar el css.

**Comment by ivantodorovich** [comment]
@sharkiller sobre que plataforma estás corriendo?

**Comment by sharkiller** [comment]
@ivantodorovich perdon era un error de mi repo. tenia instalado el nw 0.8.5
instale el 0.9.2-2 para probar ahora y and de maravilla :P

**Comment by vlasvlasvlas** [comment]
+1 en windows7 me pasa lo mismo. se cuelga si pauseas

**Comment by ivantodorovich** [comment]
Es un bug de `peerflix`, tiene que ver con el server http que hace streaming desde el archivo temporal al player.

Creo un issue y mañana intento solucionarlo. https://github.com/mafintosh/peerflix/issues/59

**Comment by fluzzi** [comment]
ahi hice un PR, no es problema de peerflix en si, sino es el comportamiento por default de nodejs. le puse timeout de 1 hora para que no pase más.

**Comment by ivantodorovich** [comment]
@fluzzi sería bueno hacerle pr a peerflix. Mucha más gente se vería beneficiada.

**Comment by ghost** [comment]
Me sumo, me pasa lo mismo en windows 7.
