### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by devguilleo** [Cuevana/storm#3]
Hola cuevana, felicitaciones por ver la posibilidad y adaptarse a los nuevas tendencias. No soy programador pero bueno me gusta aportar para mejorar transmitiendo los problemas que observe. Muy buena el diseño, el problema que veo y que me ha pasado tambien con la app original es que una vez que pongo en reproducir la pelicula, carga el torrent y empieza la reproduccion se ve la pantalla en negro nada mas, se escucha perfectamente pero en pantalla negra. Tengo win7 x64 y tengo nada mas que vlc como reproductor de video....Por favor si necesitas mas info pedimela...pq me gustaria q se resuelta este problema q es arrastrado de la original y que le afectab y va a seguir afectando a mucha gente....gracias

**Comment by devguilleo** [comment]
Copie ffmpegsumo.dll de chrome a la app pero ahora al reproducir entra al reproductor peero se queda cargando la pelicula. Sabes como pegarlo o donde? gracias

**Comment by ivantodorovich** [comment]
Usa la dll que agregó @Cuevana al repo.

La que tenés instalada de Chrome puede diferir dependiendo de la versión de Chrome que tengas instalada, te digo porque a mi me pasó eso.

PS: La tenés que copiar la dll a la carpeta del Node Webkit, donde sea que lo tenés instalado. Además tené cuidado que sea la versión 0.8.5. Yo había probado con la 0.9.2 pero con esa no anduvo.

**Comment by devguilleo** [comment]
Baje el node webkit 0.8.5 de github y copie el ffmpegsumo.dll de la carpeta de cuevana a la carpeta de node webkit bajada y no funciona la app...sigue en pantall negra.....me parece que entendi mal....soy usuario normal..sin mucho conociemiento tecnico si me podes decir paso a paso tipo nene de 2 años mejor jajaja te lo agradeceria...mil gracias

**Comment by devguilleo** [comment]
alguien solidario por ahi que ayude por favor

**Comment by ivantodorovich** [comment]
Es raro lo que comentás.. cuando tuve problemas con el codec se me veía todo negro, pero tampoco andaba el audio.

**Comment by devguilleo** [comment]
ok ivan gracias

**Comment by sharkiller** [comment]
checkea de no tener instalado la version global de nodewebkit. capaz tenes instalado el nodewebkit global de 0.9.2 y te ejecuta esa por mas que en el repo local tengas la 0.8.5
proba npm rm -g nodewebkit
pd. estas compilando vos mismo o usando el instalador de la pagina oficial?

**Comment by mairag** [comment]
Hola, tengo el mismo problema que Juan, los primeros días luego de la instalación andaba perfecto y de pronto comenzó a reproducir el sonido solo y la pantalla queda en negro. No entendí cual es la posible solución para este bug así que agradecería si alguien puede poner un paso a paso o explicación de que es lo que habría que reemplazar y donde.
Por si sirve de algo estoy usando Windows 7 (x32) y tanto Popcorn Time como Time4Popcorn me andan bien pero me gusta más la interfaz de Cuevana.
Gracias.

**Comment by sharkiller** [comment]
@mairag el de instalador o lo compilas vos?
si lo compilas vos borra la carpeta node_modules e instala todo de nuevo.

**Comment by mairag** [comment]
Gracias por responder. Estoy usando el del instalador ya que no tengo experiencia para compilarlo.

**Comment by sharkiller** [comment]
no sabria decirte entonces. posiblemente pasa por las ultimas actualizaciones de chrome

**Comment by mairag** [comment]
Ok, gracias igual por tu tiempo, seguiré investigando ;)

**Comment by Cuevana** [comment]
Prueba con la última actualización
