### ISSUE TITLE
Problema con librería libffmpegsumo para Linux de 32 bits

### ISSUE THREAD

**Issue by ghost** [Cuevana/storm#31]
La librería libffmpegsumo.so que se incluye en el repositorio para Linux de 32 bits provoca que la aplicación se cierre apenas va a comenzar la reproducción.

Esta es la salida:

<blockquote>[15448:0405/195704:WARNING:crash_handler_host_linux.cc(317)] Could not translate tid - assuming crashing thread is thread group leader; syscall_supported=1
[15448:0405/195704:ERROR:breakpad_linux.cc(1249)] crash dump file written to /tmp/chromium-renderer-minidump-8ba8af5ed33465b6.dmp</blockquote>

La que sí me funciona hasta el momento es esta que siempre uso: https://github.com/hotice/webupd8/raw/master/libffmpegsumo.so

**Comment by ghost** [comment]
Acabo de probar y esto ya no sucede haciendo uso de nodewebkit@0.9.2. La librería del repositorio funciona bien.

**Comment by cesasol** [comment]
Confirmo el resultado con nodewebkit 0.9.2 Funcionando y de maravilla

**Comment by ivantodorovich** [comment]
:+1:
