### ISSUE TITLE
Traducciones

### ISSUE THREAD

**Issue by sharkiller** [Cuevana/storm#34]
@Cuevana les interesaría manejar las traducciones así?

http://www.getlocalization.com/CuevanaStorm/

El sistema actualiza automáticamente el archivo master (que le puse que sea **en.json**) desde github cada vez que cambia y agrega las nuevas keys a todos los idiomas para que sean traducidas. 
Tiene una api para compilar las traducciones y mediante un script que hice lo deja exactamente igual que los archivos en la carpeta locales. Ni siquiera necesita estar la traducción completa 100%. Tambien genera el array allLanguages con los códigos de idioma.
Si interesa se puede hacer público y lo compilo cada un par de días y lo mando mediante un pull request.
Si no interesa me dicen y borro el proyecto.

**Comment by ghost** [comment]
@Sharkiller 
Can you put Slovenian language on that list of languages for Cuevana Storm for me to translate it, if you can? 
http://www.getlocalization.com/CuevanaStorm/

**Comment by sharkiller** [comment]
@TurnerOS they don't want this I assume. So i don't see the point to add new languages.
I think they going to stick to english/spanish

**Comment by ghost** [comment]
@sharkiller 
Thank you for telling me that.  English version will do just fine..  Maybe some other time if they reconcider to have their app in multilang, then i ask again .. :) 
Anyway do you have any idea when Eng. version might come out ?

**Comment by Cuevana** [comment]
@sharkiller disculpa la demora. Se perdió el hilo entre los otros y no pudimos contestar. Interesa tenerlo en todos los idiomas así que tu sugerencia es buena. Desde ya estamos OK con hacer merge de PR actualizando nuevos idiomas.

@TurnerOS We have no problem in adding more languages, as long as you mantain them. We will officially support English and Spanish. We can't focus on more languages, but you are more than welcome to update any other if the officials change. Just make the PR and we'll merge it to master.
