### ISSUE TITLE
El cursor no desaparece cuando está reproduciendo

### ISSUE THREAD

**Issue by rdz-rare** [Cuevana/storm#36]
Cuando el player esta en full screen y el barra de control desaparece, debería desaparecer también el cursor, de lo contrario éste no desaparece, a veces sí, es muy raro.

**Comment by sharkiller** [comment]
que version estas usando?
Esto ya fue corregido en d8948dd0168fe74b8c8f4588feadaf7e81540f2c

**Comment by rdz-rare** [comment]
Oh perfecto!!!
yo estaba usando la version 0.1 Beta (0.1b)

**Comment by DarwinJ94** [comment]
@sharkiller ¿Me podrías explicar cómo actualizar para poder tener las últimas mejoras?

**Comment by sharkiller** [comment]
no hay version publica todavia, pero si tenes idea mas o menos de computación prob compilando vos mismo. Aca tenes un poco de ayuda #2

**Comment by rdz-rare** [comment]
Gracias! eso es lo que estaba preguntando, cómo compilarlo!

**Comment by juanmacio** [comment]
Sigue sin desaparecer el cursor...
