### ISSUE TITLE
Resize player to fit 16:9 screen

### ISSUE THREAD

**Issue by fluzzi** [Cuevana/storm#37]
La mayoria de las peliculas tienen formato mas grande que 16:9 (tamaño normal de las pantallas) por lo que se ven las barras negras. usualmente en reproductores como VLC u media player uso un zoom que se llama fit o cut 16:9 que basicamente agranda el video hasta que cubre las barras negras (obviamente se pierden los bordes izquierdo y derecho pero no deformas la imagen)

sera posible agregarle zoom por el estilo para evitar las lineas negras?

gracias!

**Comment by sharkiller** [comment]
hacer eso perdes la mitad de la pelicula. osea preferis no ver 50% de la pelicula por no ver unas barras negras que ni se notan?

**Comment by ivantodorovich** [comment]
Decí que el comentario fue en español porque no se como decir "gronchada" en ingles..
Personalmente es algo que nunca, pero nunca, usaría. Sin embargo como dice @fluzzi , VLC y otros reproductores lo tienen.. así que debe ser un feature solicitado. Mi voto no deja de ser :-1:

**Comment by Foxito** [comment]
Totalmente de acuerdo, o mejor dicho, en desacuerdo, para mi no se justifica en una serie o pelicula, recortar los bordes teniendo que sacrificar parte de lo que se deberia ver. Yo tengo esa opcion en un LCD Sony y la uso solamente para ver los partidos de futbol, porque la camara siempre se centra en la pelota asi que no importa mucho lo que te perdes y te permite ver todo proporcional en lugar de un partido de enanos.

Pero bueno, en este caso para films y series no le veo utilidad. Tambien pulgar para abajo.

**Comment by Cuevana** [comment]
No está en los planes por ahora.

**Comment by cabrote** [comment]
Totalmente de acuerdo. Jamas uso reproductores multimedia que no permiten elegir zoom personalizados. Por eso siempre estoy firme con el XBMC que permite todo tipo de personalizacion. Actualmente uso XBMC + Addons de Torrents y es maravilloso. Sin embargo Cuevana tiene un diseño hermoso pero carente de personalizacion.

Jamas veo una peliculas con franjas negras arriba y abajo, achica bastante la pantalla. Prefiero perderme algo de los costados de la pelicula, lo principal sucede en el centro. O como se piensan que ven las peliculas por cable?

Deberian agregar una opcion de zoom parejo (1:35) para agrandar el centro de la imagen. Es una simple opcion que deben agregar como el resto de los programas reproductores (Zoom normal, original size, 1:35, etc).

Saludos. Muy linda interface.

**Comment by fluzzi** [comment]
se puede agregar, es bastante facil lo hice para la version vieja y no lo pasaron, ahroa no estoy pudiendo laburar en el nuevo, pero si alguno se anima, basicamente hay que agarrar el player y cambiarle el css style object-fit, las opciones son cover para que cubra la pantalla sin cambiar de aspect, y contain para mantener el "default" de las franjas.
