### ISSUE TITLE
Subtitles not loading on Mac

### ISSUE THREAD

**Issue by rodvilla** [Cuevana/storm#43]
Hi. The subtitles are not working for me on Mac. I am on OS X 10.9.2, I choose Spanish and it says "Loading" but never loads. Thanks for such an amazing app!

**Comment by ivantodorovich** [comment]
Does this happen on all subtitles or just a few?

Does loading subs from local files work?

**Comment by fmquaglia** [comment]
hi @ivantodorovich same issue than @rodrigovilla33 here.

The subtitle option chosen by default is "Ninguno", and Spanish and English are grayed-out and show _Loading..._ but they never finish to load.

I only saw a working spanish subtitle once.

I'm willing to help.

**Comment by gabrielfagundez** [comment]
I am not able to see the comments on OSX. It shows Loading..
