### ISSUE TITLE
Informar cantidad de seeds disponibles para cada pelicula / serie

### ISSUE THREAD

**Issue by guidocelada** [Cuevana/storm#44]

**Comment by ivantodorovich** [comment]
La sugerencia sería mostrarlos ANTES de apretar el boton de reproducir?

Si es así, en lugar de ser tan específico preferiría mostrar la "Salud" del torrent. Que sería basicamente lo mismo, pero con un poco de procesamiento técnico para que cualquier usuario sepa lo que está viendo sin siquiera conocer lo que es un SEED.

Nosotros nos encargaríamos de evaluar si la cantidad de seeds/leechers es buena, regular, o mala, y mostrar dicha información al usuario.

![wifi 1](https://cloud.githubusercontent.com/assets/1914185/2658618/c296c630-c00a-11e3-8858-7b8738491f54.png)

**Comment by vlasvlasvlas** [comment]
+1

**Comment by vlasvlasvlas** [comment]
no solo ver el dato sino poder "ordenar por" este dato seria ideal

**Comment by lbonini** [comment]
+1

**Comment by Cuevana** [comment]
Hecho en la nueva versión. Saludos
