### ISSUE TITLE
No video on Mac OS 10.8.5

### ISSUE THREAD

**Issue by batsteek** [Cuevana/storm#49]
I have been playing with numerous versions of ffmpegsumo.so, including the one from the Storm binary found on http://www.cuevana.tv/ (which work fine) and I still get no video from the github sources.

I mean, everything is ok (except for the english subtitles missing unfortunately ...) but no video.

Mac OS 10.8.5

**Comment by batsteek** [comment]
So I am alone with that particular issue ?

**Comment by ivantodorovich** [comment]
Please try deleting `node_modules` folder and reinstalling dependencies. with `npm install`. 
Then run with `npm start`.

This will ensure you are running the right version of nw, and will also handle ffmpegsumo.

**Comment by batsteek** [comment]
well ... thanks a lot @ivantodorovich , I did everything according to your recommendations but got the same issue.

I see that the torrent is loading fine, many seeds and so on, the subtitles are ok, but the player stays black and remains at 00:00 ...

note: and unfortunately, the logs are not talkative enough (at least for me to understand the issue)

**Comment by ivantodorovich** [comment]
> note: and unfortunately, the logs are not talkative enough (at least for me to understand the issue)

Are there any logs? Or just blank

**Comment by batsteek** [comment]
Well, my "technical" knowledge is quite poor but I see nothing related to ffmpegsumo.so or the player.... 
Any idea where I should have a look ?

**Comment by batsteek** [comment]
Regularly updating the source from github ... still no video ...
I'm sad ! ;)

**Comment by Cuevana** [comment]
Should work. Try now.

**Comment by caparkove** [comment]
Hi, I'm using cuevana on Windows 7 and when I select the movie it stops at 00:00 and then stops working. I don't know anything about computers :(
