### ISSUE TITLE
No me aparece la barra de carga ni los botones de control de video

### ISSUE THREAD

**Issue by maarianpe** [Cuevana/storm#52]
Tengo un enorme problema y es que directamente no aparecen los botones para pausar, reproducir, control de volumen, opción de subtítulos, ni la barra donde veo cuánto ha cargado la película, tampoco aparece el botón para full screen y deblo cliquear 3 veces sobre el video para poder tenerlo en full pero no poder poner pausa ni adelantar escenas es algo realmente muy molesto! Ya intenté reinstalar la app, puede deberse a que utilizo windows 7 de 64 bits? es muy raro lo que me ocurre porque no se de nadie más a quien le pase. Agradecería mucho su ayuda!

**Comment by fluzzi** [comment]
Buen día, este issue es por un problema en cómo detecta el touch la aplicación y ya fue solucionado, que versión estas usando? La que esta en la pagina de cuevana?

**Comment by Foxito** [comment]
Yo tambien uso W7 de 64 bits y no tengo ningun problema con la  barra, esta version anda muy bien y con la mejora que hizo @ivantodorovich para que sea mas facil instalar y ejecutar la app es muy facil hacerlo, si tenes problemas postea otra vez que trato de ayudarte.

Yo el problema que tengo con la barra de controles es que aparece cada tanto sin que se toque nada, muestra el cursor y aparece la barra, a veces es molesto porque te sube los subtitulos y pasa cada un par de segundos, y otras veces esta durante varios minutos sin aparecer. es muy random.

**Comment by maarianpe** [comment]
Es realmente muy raro lo que ocurrió, les paso a explicar. Mi PC de escritorio es una all in one con pantalla touch y cuevana no me reconocía el mouse, es decir sólo podía hacer tres clics rápidos para maximizar la ventana y nada más, ninguna otra función u opción. Admito que jamás se me hubiera ocurrido tocar con el dedo la pantalla pero por lo menos ahora sí funciona, la app me reconoce el dedo  y aparece la barra! Sigue siendo un poco incómodo porque no puedo controlar la app a la distancia pero en sí es un problema menos. Muchas gracias por la ayuda!

**Comment by Cuevana** [comment]
Lanzamos nueva versión, debería haberse solucionado este problema.
