### ISSUE TITLE
Torrents con low Seeds

### ISSUE THREAD

**Issue by ivantodorovich** [Cuevana/storm#53]
¿A alguien más le parece que algunos torrents bajan lento? Especificamente, que tienen pocos Seeds?

Generalmente no me cargan mas de 5~10 seeds cuando arranca, y de ahí no sube.. cuando abriendo el mismo magnet con uTorrent sí conecta a muchos Seeds.

Estuve investigando y creo que está relacionado con este issue de torrent-stream/peerflix: https://github.com/mafintosh/torrent-stream/issues/14 donde se dice que el DHT no está funcionando correctamente.

Después lo voy a investigar con más detalle, pero es posible que torrents donde el tracker no registre muchos clientes se note bajo rendimiento debido a esto.

**Comment by ivantodorovich** [comment]
Comprobado, edité el `package.json` de `node_modules/peerflix` para que requira `torrent-stream@0.4.1` en lugar de la `0.5.0`.

La mejora fue evidente. Mismo torrent, pasar de 6 Seeds como máximo a más de 20 y rápidamente incrementando.

Realmente no depende de Storm soluciuonarlo, pero sí podemos elegir qué version de `peerflix` requerir. Más tarde hago un PR con el FIX.

**Comment by ivantodorovich** [comment]
Hice un par de PR para arreglar esto.

https://github.com/feross/bittorrent-dht/pull/7
https://github.com/mafintosh/peer-wire-swarm/pull/6

Cuando sean publicadas va a haber que actualizar el `package.json` para usar la versión corregida de `peerflix`.

Lo testie y con los torrents que tienen pocos seeds mejora muchísimo el rendimiento.

**Comment by Foxito** [comment]
Muy bueno, a mi me pasaba a la noche con los capitulos de Da Vinci's Demons S01, por algun motivo me cargaban como decis vos 5 o 6 seeds y se freezaba cada 5 segundos, pero de dia andaban bien.

**Comment by fluzzi** [comment]
Lo probé y Funciona perfecto., ya están los 2 pr?

**Comment by ivantodorovich** [comment]
El del swarm si, pero el administrador de bittorrent-dht hace varios días no se conecta, y no lo aprobó todavía.

**Comment by fluzzi** [comment]
ya esta peerflix actualizado a la 0.8.2 con todos estos cambios

**Comment by nchiari** [comment]
Hola gente, soy un user de Windows comun y corriente sin conocimientos de programacion algunos. Estuve googleando sobre este tema de que Cuevana Storm anda lento de noche y me encontre con este post en el que veo que pudieron solucionarlo. Como la verdad no tengo ni la mas palida idea de que estan hablando, se me ocurrio preguntarles si existe alguna forma de que nosotros los "mortales" que no cazamos una de codigo podamos usar este fix que crearon acá. De ser asi agradeceria que me dieran un tutorial o algo para poder aplicarlo.

Saludos y gracias!
