### ISSUE TITLE
[OSX] PopCorn Time reproduce fluido Storm se pega

### ISSUE THREAD

**Issue by chrissmejia** [Cuevana/storm#55]
No son los mismos torrent porque el otro está solo en inglés pero definitivamente algo se copió mal, la misma película se pega en Storm y se reproduce fluido en PopCorn Time, además de que de tanto en tanto pega la Mac, la tasa de descarga o transferencia se mantiene en unos 300KB/s.

**Comment by ivantodorovich** [comment]
Probablemente está relacionado con https://github.com/Cuevana/storm/issues/53.

popcorn-time utiliza `peerflix@0.1.6`, y eso es antes del commit mencionado en ese issue.

Hay un issue creado en el repositorio de `torrent-stream` donde se está intentando resolver este problema. Por ahora tenemos 2 opciones: hacer downgrade de `peerflix` o esperar a que se solucione que, con suerte, sería dentro de poco.

**Comment by chrissmejia** [comment]
Gracias por la respuesta, a ver si los administradores sacan también binarios más seguido, para que los mortales también puedan disfrutar de las mejoras.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
