### ISSUE TITLE
traducir géneros | Translate Genres 

### ISSUE THREAD

**Issue by ghost** [Cuevana/storm#56]
Noté algo de él fue localizado en Inglés sería posible traducir la lista de géneros también?

Buen trabajo en la aplicación hasta ahora!

---

Noticed some of it was localized in english would it be possible to translate the genre list as well?

nice work on the app so far!

![](http://i.imgsnap.tk/image.php?i=72811fd842828a896fa26fe6222fc01d9193a24dcc5b268b94d24dcc)

**Comment by Cuevana** [comment]
Done. ed1b87164fdfaa99ab6d355786b0163ba1daa3ee
