### ISSUE TITLE
No se reproduce nada

### ISSUE THREAD

**Issue by ramamaciel** [Cuevana/storm#58]
Despues de elegir la pelicula, se me abre una pestaña nueva con el reproductor.
 Me aparecen los clientes bajandose y todo, pero esta en play y se queda en 00:00 y no avanza. No empieza la pelicula y se queda ahi! 
Puse pausa y le di play de nuevo y nada!
Tengo windows7
:)

**Comment by batsteek** [comment]
Same issue here https://github.com/Cuevana/storm/issues/49 (but on a Mac)

**Comment by yoeluru** [comment]
A mi me pasa lo mismo en mac con Mavericks...

**Comment by Foxito** [comment]
a mi me pasaba lo mismo. Les pasa al bajar la app de la pag de cuevana? o despues de compilar los archivos de aca?

**Comment by pandev92** [comment]
Tengo exactamente el mismo problema, en ubuntu 14.04, increiblemente, la versión de windows, si la uso con wine, si reproduce, pero la de linux, nunca pasa del 00:00

**Comment by gpiotti** [comment]
mismo problema, solo en windows y con los archivos compilados

**Comment by gpiotti** [comment]
SOLUCION:
para que funcione hay que hacer la build a mano copiando los contenidos de:
\node_modules\nodewebkit\nodewebkit a una carpeta
y arrastrando la carpeta completa de la app (en mi caso 'storm') arriba de nw.exe

parece ser que el script que hace el build, copia otras dependencias que no funcionan

**Comment by gpiotti** [comment]
el problema es el archivo ffmpegsumo.dll. El que sirve esta en \node_modules\nodewebkit\nodewebkit.
El que se baja automaticamente con el script de build no sirve

**Comment by ivantodorovich** [comment]
El script de build baja uno que no sirve, pero luego lo sobreescribe con el que sí sirve. Al menos eso es lo que debería hacer. En mi PC (win7 x64) lo hace sin problemas.

**Comment by fluzzi** [comment]
A mi me pasa lo mismo, parece que el script para copiar no funciona en algunos casos, me pasa con win 7 y 8 de 64

**Comment by nicoalfonso** [comment]
Alguien me puede explicar qué es "node_modules\nodewebkit\nodewebkit"? No tengo ni idea de programación y tengo el mismo problema que la persona que abrió el thread. Gracias!

**Comment by eduardobarrera** [comment]
Alguien puede explicar como hacerlo? a mi tampoco me pasa del 00:00

**Comment by auledoom1** [comment]
Mismo problema en ubuntu 14.04 x64bits, el problema parece ser que el script no detecta correctamente la arquitectura y copia la librería  ffmpegsumo.so de 32 bits. Si copio manualmente desde storm/deps/ffmpegsumo/linux64/ a storm/node_modules/nodewebkit/nodewebkit/ funciona correctamente. Ahora le haré una miradita al build script a ver si tengo suerte :D

**Comment by aecc** [comment]
Copiando la libreria desde /deps/ffmpegsumo/win/ffmpegsumo.dll al directorio del buiild en /build/Cuevana/win/ solucionó mi problema en Windows 7 32-bit

**Comment by guarro** [comment]
Hola alguien puede explicar paso a paso como se hace, para los que no sabemos nada de programación. O por favor si se puede subir el archivo corregido. En mi caso en windows 7 32 bit no funciona y en windows 8.1 32 bits si, porque??? Desde ya gracias.

**Comment by julianabarillaro** [comment]
Hola, quisiera saber cómo poder realizar ese arreglo, y en qué ubicación se encuentra la carpeta en la que debe realizarse.

**Comment by Mato2014** [comment]
Tengo el mismo problema pero no encuentro la ruta del archivo que hay que copiar. Alguien puede indicar como acceder?

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by olivercs** [comment]
El problema persiste en OS X mavericks

**Comment by Cuevana** [comment]
@olivercs desde la app ejecutable o corriendo `npm start` desde el repositorio?

**Comment by olivercs** [comment]
Desde ambas...

Corriendo npm start obtengo el siguiente error en devtools: undefined is
not a function en player.min.js.

Lo reemplace por player.js y por alguna razón el método play() para el
vídeo no esta funcionando si intento usar el tag vídeo tampoco.

En la aplicación si añado al index.html en la caperta views un tag de vídeo
para probar. Los vídeos si se reproducen sin embargo en el player no pasa
esto. La pantalla siempre negra.

**Comment by Cuevana** [comment]
Faltaba incluir bower update dentro del script de instalación. Igualmente debería funcionar bien la versión empaquetada. Vamos a investigar a ver si podemos encontrar el motivo.
Cualquier dato adicional ayudaría. Gracias.

**Comment by olivercs** [comment]
Bueno si tomo la url del video usando npm start. Puedo visualizar el video
desde el navegador.
Sin embargo si lo hago desde la app ya compilada,me es imposible.

Si necesitan cualquier dato para prueba pueden preguntarme...

El 17 de septiembre de 2014, 3:26, Cuevananotifications@github.com
escribió:

> Faltaba incluir bower update dentro del script de instalación. Igualmente
> debería funcionar bien la versión empaquetada. Vamos a investigar a ver si
> podemos encontrar el motivo.
> Cualquier dato adicional ayudaría. Gracias.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cuevana/storm/issues/58#issuecomment-55858266.

## 

Best,
Oliver

**Comment by olivercs** [comment]
Asi solucione el problema en la version compilada:

node/playtorrent.js:55

Cambiar:
var href = 'http://'+address() +':'+engine.server.address().port+'/';
Por:
var href = 'http://'+engine.server.address().address +':'+engine.server.address().port+'/';

**Comment by Cuevana** [comment]
@olivercs muy buen aporte! Parece que ese era el problema por el cual algunos no estaban pudiendo reproducir. Ahora actualizamos el repositorio con este cambio. Gracias!

**Comment by krill96** [comment]
muchas gracias @olivercs, si me funcionó

**Comment by nacho02** [comment]
Hola, tengo el mismo problema. No me doy cuenta como cambiar eso que hay que cambiar. Reinstale el programa y me sigue pasando lo mismo. Alguien me puede guiar paso a paso por favor? Ni se donde encontrar esas carpetas que mencionaron.
Gracias

**Comment by Tri4c3** [comment]
El mismo problema en win 8.1 x64 ... abro desde carpeta temp y veo el video y me corre con vlc pero desde la App no corre. Favor actualizar el archivo de instalación que esta en la Web para nosotros los simples mortales que no compilamos aplicaciones.

**Comment by josealvaradoo** [comment]
Tengo Windows 7 x64 y al dar click en reproducir, al elegir la resolución aparece S:0 | P:0 Y al elegir una de las resoluciones dice "Buscando clientes" pero no encuentra ninguno. Bajé la aplicación compilada desde la página de cuavana.

¿Alguna solución? :P

**Comment by olgabart** [comment]
Hola a todos,
A día de hoy continúa el problema, cuévana carga las pelis pero no pasan de 00.00.
Desde que instalé mavericks....hasta hoy.

**Comment by CAMIZOCA** [comment]
Mac Software OS X 10.9.5  se queda en 00:00

**Comment by realgigio** [comment]
Qué tal, yo tenía instalado el Cuevana Storm y funcionaba perfectamente, cuando atcualicé al Yosemite (OS X 10.10) Todos los videos me salen que no agarran los torrentes (el indicador de torrent healt me sale en rojo) y si alguno logra conectarse, no sale el video...

**Comment by krakoshi** [comment]
Hola, yo tengo un problema distinto, eligo el torrent para reproducirla y dsp de buscar se pone en negro la aplicacion y se cierra... saben por q sera?

**Comment by eduarso** [comment]
cuevana storm funciona en MAC OS 10.5 ? -leopard en imac g5, power pc no intel-

**Comment by RICARDOQA** [comment]
yo  tengo windows xp 32 bits , la aplicacion me daba error falta archivo dbgeng.dll, no cargaba, se quedaba en negro y se cerraba solo;  descargue el archivo faltante  y lo pegue en la carpeta sistem 32, despues fui a propiedades - compatibilidad y ejecute el programa en windows 98 y me funciono.. ahora ya veo las peliculas sin ningun problema.. espero le sirva a alguien con el mismo sistema operativo.....

**Comment by boxer16** [comment]
Hola, tengo el mismo problema con el OS X 10.9.5, hoy intenté con otras series y funcionó con "Agents of Shield", pero las que estaba viendo antes del problema, como "Two broke girls" sigue quedando en 00:00 a pesar de que aparece descargando de varios clientes en un principio hasta que al cabo de unos segundos se detiene también la descarga. hice el cambio que aconseja @olivercs pero no funciona. Ojalá puedan orientarnos. Muchas Gracias.

**Comment by krill96** [comment]
@boxer16 en ciertas peliculas/series tengo el mismo problema, finalmente llegue a la conclusion que es problema de estas (y no del reproductor), que no tienen la disponibilidad (el archivo completo) para comenzar la reproduccion

**Comment by michelson** [comment]
el mismo problema por acá , en OSX , probé la app empaquetada y usando la de este repositorio también.

viendo el log con `npm start` veo dos errores, 

el primero cuando el video está cargando y queda en negro aparece lo siguiente en la traza del log:

[77814:1227/235607:INFO:CONSOLE(67)] "{}", source: app://cuevana/app/js/app.js (67)
[77814:1227/235607:INFO:CONSOLE(9761)] "Uncaught TypeError: Cannot read property 'statusText' of null", source: app://cuevana/bower_components/angular/angular.js (9761)

y cuando presiono el botón Play aparece lo siguente en el log:

[77814:1227/235621:INFO:CONSOLE(11594)] ""TypeError: undefined is not a function\n    at Scope.h.play (app://cuevana/bower_components/angular-media-player/dist/angular-media-player.min.js:1:1489)\n    at Scope.h.playPause (app://cuevana/bower_components/angular-media-player/dist/angular-media-player.min.js:1:1671)\n    at Scope.scope.togglePause (app://cuevana/app/js/directives/stPlayerControls.js:133:18)\n    at $parseFunctionCall (app://cuevana/bower_components/angular/angular.js:12332:18)\n    at callback (app://cuevana/bower_components/angular/angular.js:22949:17)\n    at Scope.$eval (app://cuevana/bower_components/angular/angular.js:14383:28)\n    at Scope.$apply (app://cuevana/bower_components/angular/angular.js:14482:23)\n    at HTMLAnchorElement.\u003Canonymous\u003E (app://cuevana/bower_components/angular/angular.js:22954:23)\n    at HTMLAnchorElement.jQuery.event.dispatch (app://cuevana/bower_components/jquery/dist/jquery.js:4430:9)\n    at HTMLAnchorElement.elemData.handle (app://cuevana/bower_components/jquery/dist/jquery.js:4116:28)"", source: app://cuevana/bower_components/angular/angular.js (11594)

**Comment by jotaltamirano** [comment]
Me funciona con algunas series y no con otras ni con películas.  Hice lo recomendado por @olivercs, pero no vi cambios.

**Comment by shiaio** [comment]
a mi me paso igual que a ti @michelson  ya pudiste resolver??? lo descargue y no se queria instalar, lo instale y me sale esa ventana y otra ventana que si lo habre y la que si lo abre trate de poner una pelicula y no encuentra clientes y no la reproduce

**Comment by caparkove** [comment]
Necesito ayuda, la película se queda en 00:00 y veo que muchos ponen soluciones pero no sé nada de computación así que no sé cómo arreglarlo. Espero que me puedan ayudar.

**Comment by Tri4c3** [comment]
si nunca arreglaron el programa mejor instala popcorn saludos

Gerik G. B. Zambrano Caballería
Proyectista & Modelador 3D
Cel: (09) - 50909576 - Hangout: gerik.zambrano@gmail.com
http://rendermachine.wordpress.com

**Comment by shiaio** [comment]
Hola,  instale popcorn pero no reproduce las películas (en ninguna compu),
no se porque, además cuevana ya lo había instalado en 3 laps y todo bien y
con la de muy sobrina no quiso

**Comment by Tri4c3** [comment]
EXISTEN DOS PORCORN... A MI UNO ME FUNCIONA EL OTRO NO.

Gerik G. B. Zambrano Caballería
Proyectista & Modelador 3D
Cel: (09) - 50909576 - Hangout: gerik.zambrano@gmail.com
http://rendermachine.wordpress.com

**Comment by shiaio** [comment]
Ooooo tienes de casualidad el lino del popcorn bueno?? O tiene algún nombre
en especial??? Gracias

**Comment by paulinadeita** [comment]
no se ve nada en cuevana literal abro el programa y no sale nada, solo me pasa a mi? que hagoo porfa diganmeee

**Comment by karijrz** [comment]
a mi tambien me pasa...@paulinadeita....y aun no puedo arreglarlo PORFAVOR alguien sabe como solucionarlo??

**Comment by josealvaradoo** [comment]
Hola. A mi tampoco me aparece nada al abrir la aplicación. Solo aparece el menú.

**Comment by manelet** [comment]
corroboro, que no carga contenido la app en mac

**Comment by inescerv** [comment]
Meeeooww! Nada de nada :c ayuda para los que no entendemos su el lenguaje técnico por favor.

**Comment by ElaineBenes** [comment]
A mi, cuando apretó reproducir se pone la pantalla negra y cuevana se cierra. A alguién más le pasa esto? Tengo windows 7.

**Comment by SCuevana** [comment]
Saludos a todos en especial a los amigos emprendedores de Cuevana, he disfrutado de la extraoridnaria experiencia que ofrecen pero ultimamente no puedo reproducir ninguna pelicula, hasta hace poco me sucedia a veces solo con algunos titulos pero ahora es con todas las que intento reproducir y ya he reinstalado en varias oportunidades la app y nada. Espero puedan solucionar pronto!
