### ISSUE TITLE
I can't compile for mac

### ISSUE THREAD

**Issue by enzolutions** [Cuevana/storm#59]
I tried to compile the program from sources and get this error

$ npm run build

> Cuevana@0.2.0 build /Users/enzo/www/storm
> gulp build

[gulp] Using gulpfile /Users/enzo/www/storm/gulpfile.js
[gulp] Starting 'build'...
Mac is not supported yet.
[gulp] Finished 'build' after 120 μs

**Comment by ivantodorovich** [comment]
`build` is only required to pack your app into a distributable binary. It's an automated process that follows https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps guidelines.

Right now only Windows is supported, but you can pack it yourself following those guidelines.

I'm working on automating `build` processes for mac and linux, I'll make a PR.

**Comment by ivantodorovich** [comment]
See PR https://github.com/Cuevana/storm/pull/61

**Comment by gianpaj** [comment]
:+1: looking forward to this.

**Comment by gianpaj** [comment]
this can be closed. if you have problems installing nodewebkit, do this:
`npm install nodewebkit@0.9.2-4`

Then for OS X:
- `npm run build`
- `open build/Cuevana/osx/node-webkit.app`

**Comment by Cuevana** [comment]
Fixed. 221640a93b9cceacf20157dad06e6a482f467f17
