### ISSUE TITLE
Regarding Gulp

### ISSUE THREAD

**Issue by ivantodorovich** [Cuevana/storm#6]
Everytime a change is made, gulp generates new css/js files, with different names than the old ones.

Git won't be happy with this.. and the repository will get bigger and bigger on each change.. since the old files will always stay in the repo history.

So I wonder.. is it really necessary to minify and inline css/js?

If it were, shouldn't we remove compiled files from the repo? (.gitignore)

**Comment by Cuevana** [comment]
Good point. For now, we can ignore js and css directories.

**Comment by ivantodorovich** [comment]
Made a PR to completely ignore Gulp generated files.

index.html and player.html will keep changing every time gulp generates files, because of the continious renaming of lib-_.js and main-_.css

I'm sorry I have to ask again, is this really necessary? I mean, cache should't be a problem here.. so what's the point?

**Comment by ivantodorovich** [comment]
@Cuevana te pregunto.. cual es la finalidad de concatenar y revisionar los *.css y *.js?

En un webserver lo entiendo, pero un app de node-webkit no me cierra, sobre todo si el código es libre.

Tranquilamente podríamos injectar los assets originales, sería mucho más facil de debuggear. No te parece? 

Además, como beneficio extra, index.html y player.html dejarían de ser modificados con cada cambio, git estaría tranquilo con eso y el repositorio estaría siempre en un estado listo para ser ejecutado, sin la necesidad de gulp (sólo haría falta para developers)

Me estoy perdiendo de algo?

**Comment by cesasol** [comment]
Bueno, git está hecho para devolpers y testers

**Comment by Cuevana** [comment]
Estamos removiendo gulp, comentando algunas secciones, además de añadiendo localización. Haremos un push en algunos minutos.

**Comment by ivantodorovich** [comment]
Ok @Cuevana, genial! Lo veré mañana porque me estoy yendo :+1: 

@cesasol For the record.. mi sugerencia no era remover gulp completamente, sólo las tareas de concatenación y de revisión, ya que son las que molestan a la hora de debuggear. No tengo nada en contra de gulp, de hecho me parece muy útil, en este caso para compilar less y la inyección de html
