### ISSUE TITLE
elegir fuente de torrents

### ISSUE THREAD

**Issue by vlasvlasvlas** [Cuevana/storm#60]
Hola, 

estaba pensando que sería buena opción que el usuario final pueda agregar su propia fuente de torrents para ver en streaming,

sobre todo pensando en usuarios que participan de sitios de torrent privados (esto haria que la app la pueda usar mucha mas gente también)

como la ven?
saludos

**Comment by ivantodorovich** [comment]
Sería muy bueno, la verdad!

:+1:

**Comment by ivantodorovich** [comment]
Me gustaría ver una versión del API más flexible, donde tanto las fuentes y los subtitulos que los usuarios agregan fuesen subidos a Cuevana, y compartidos automaticamente.

No digo que estén al mismo nivel que las fuentes que Cuevana selecciona, pero si bajo una opción de sugerencias.. 

La comunidad misma ayudaría a incorporar material, y a mejorar la calidad del contenido! Incluso podría haber un sistema de votación para clasificar las fuentes/subtitulos, Cuevana podría "Verificarlos" cada tanto, para que sean tratados como "oficiales".. les sería mucho más facil que buscar las fuentes y subtitulos por su cuenta!

Además hay muchas series que no tienen fuentes actualmente, ayudaría muchisimo a popularlas.

**Comment by vlasvlasvlas** [comment]
de que forma podemos ayudar en esto? no encuentro en la fuente donde se declare los torrents, si alguien me da alguna indicación me pongo manos a la obra

**Comment by Marambelo** [comment]
La nueva version de get-popcorn.com tiene para hacer drag and drop del torrent se podria ver la manera que lo implentaron ellos.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, incluye esta funcionalidad llamada URL. Saludos.
