### ISSUE TITLE
ordenar por pelis con + seeds

### ISSUE THREAD

**Issue by vlasvlasvlas** [Cuevana/storm#63]
Hola! una buena opción podria ser poder ordenar las pelis y series con mayor cantidad de torrents seedeados, y asi poder elegir de entre las pelis mas fluidas.

**Comment by guidocelada** [comment]
Duplicado de #44

**Comment by Cuevana** [comment]
Ahora se pueden ver las seeds de cada fuente. Pero cada película/episodio puede tener múltiples.
