### ISSUE TITLE
Me desconecta de internet

### ISSUE THREAD

**Issue by nitepunk** [Cuevana/storm#64]
Al estar utilizándo la app me desconecta de mi conexión inalambrica, ocurre mas rápido si adelanto la película o serie, y no importa que velocidad se este descargando, ya que me ha bajado a 70 kb/s o a 700 y ocurre. ¿Porqué sera esto?

**Comment by kas84** [comment]
Esto creo que puede ser porque abre demasiadas conexiones en los torrents. Yo he modificado el código en mi local para que el máximo de conexiones sea 30 en vez de 100 y parece que aguanta.

**Comment by ivantodorovich** [comment]
Es exáctamente por eso, y por mal manejo de las conexiones por parte de `peerflix`.

Se está trabajando para mejorar este problema.

**Comment by Cuevana** [comment]
Solucionado.
