### ISSUE TITLE
Subtitulos se quedan en (Loading)

### ISSUE THREAD

**Issue by juanvisbal** [Cuevana/storm#65]
Algunas veces, el video el empieza a cargar pero los subtítulos no. En el menú, sale "Español (Loading)" e "Inglés (Loading)", y nunca cargan.

**Comment by ivantodorovich** [comment]
Y qué pasa si los seleccionas igual? No terminan de cargar? Realmente no me ha pasado nunca que no carguen, sí me ha pasado que tarden.

**Comment by ItsWendell** [comment]
I'm currently busy writing full-on support for OpenSubtitles.org with the ability to choose from every language available. I already pushed a version with subtitle support for english subtitles only. Check the forked version that I applied.

**Comment by juanvisbal** [comment]
@ivantodorovich Después de varios minutos, se queda igual y nunca cargan. No importa si los selecciono.

**Comment by Foxito** [comment]
A mi me paso lo mismo varias veces, incluso si cerras la peli o capitulo y volves a abrirla, no se soluciona, tuve q cerrar y volver a abrir la app para que funcionara, y siempre funciono al primer reinicio, nunca paso dos veces consecutivas.

**Comment by Cuevana** [comment]
Estuvo pasando en estos días por un problema de resolución de DNS. No debería seguir ocurriendo. Avisen si les continua pasando.

**Comment by lbacigalupi** [comment]
sigue pasando...

**Comment by ajatib** [comment]
si, sigue pasando

2014-05-25 20:25 GMT-03:00 lbacigalupi notifications@github.com:

> sigue pasando...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cuevana/storm/issues/65#issuecomment-44148618
> .

## 

Alejandro Jatib

**Comment by Maxerox** [comment]
Me pasa exactamente lo mismo el video carga al toque los subtitulos quedan en loading y nunca cargan

**Comment by laguardiarg** [comment]
Sigue pasando quedan en español loading

**Comment by ajatib** [comment]
Que pasa con esto y porque no contestan nada al respecto? se va a
solucionar?

2014-05-30 20:35 GMT-03:00 laguardiarg notifications@github.com:

> Sigue pasando quedan en español loading
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cuevana/storm/issues/65#issuecomment-44710532.

## 

Alejandro Jatib

**Comment by Dazu** [comment]
sigue pasando! arreglenlo porfavor!

**Comment by alarrosa14** [comment]
Me está pasando con el último de Game of Thrones

**Comment by rodzurek** [comment]
nunca carga los subs

**Comment by frantino** [comment]
Hola sigue pasando lo de los subtitulos!! me pasa con los ultimos capitulos de la segunda temporada de hanniball
