### ISSUE TITLE
Problemas con filtro para todas las peliculas

### ISSUE THREAD

**Issue by fluzzi** [Cuevana/storm#67]
Hay un problema con la api de cuevana, cuando pones filtros cuando estas en todas las peliculas no funciona el filtro

el request qeu hace es el siguiente

http://api.cuevana.tv/movies/all?genre=7

y te devuelve todas las peliculas cuando me tendría que dar las de animación. Lo mismo pasa con series en "all"

esto fue reportado con el issue #30 que esta cerrado pero el problema persiste.

**Comment by ivantodorovich** [comment]
Sí.. es cierto. @Cuevana por casualidad hay intenciones de liberar el API? Estoy seguro que podemos ayudar con este tipo de cosas.

**Comment by Cuevana** [comment]
Queremos abrir la API. La documentaremos un poco mejor y la abrimos.
