### ISSUE TITLE
No abre

### ISSUE THREAD

**Issue by Santi0608** [Cuevana/storm#68]
Hola , mi problema es que al abrir el cuevana storm, se queda minimizado, y no se puede maximizar de ninguna manera, ya probe todo, ayuda! :S

**Comment by jerdom33** [comment]
Es verdad. Esto pasa en Windows 8.1 x64 para mi tambien. No va de 1 mes o algo. Antes no tenia este problema. Solo aparece el icon en taskbar, pero nada mas. No se ve el app abrido.

**Comment by facupedrazzini** [comment]
Me pasa lo mismo en mi notebook con windows 8, descubri que es como que queda oculto en una segunda pantalla (que en mi caso esta desconectada). Lo soluciono enchufando la 2da pantalla por hdmi y aparece.

**Comment by bustedvillain** [comment]
Este problema ocurre cuando se utiliza Cuevana Storm conectado a otra pantalla, monitor o TV con la configuración de escritorio extendido. La forma de solucionarlo es seleccionar la ventana de Cuevana Storn y puslar la tecla de Windows + Dirección de Flechas (Izquierda o derecha) hasta que aparezca en la pantalla principal. Si tu monitor lo tenias extendido hacia la izquierda por ejemplo tendras que pulsar Windows+Flecha Derecha.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
