### ISSUE TITLE
No puedo instalar dependencias

### ISSUE THREAD

**Issue by fluzzi** [Cuevana/storm#72]
desde ayer que no puedo instalar ningún dependencias con npm install

me tira un error con esta linea 
"node-webkit-builder": "mllrsohn/node-webkit-builder"

lo pase a esta y funciono:
"node-webkit-builder": "~0.0.2"

pero no quiero meter mano porque no se que estoy tocando. @Cuevana o ivan?

**Comment by fluzzi** [comment]
tambien cuando hago npm run build, me crea para win un nw pelado nose porque.
y el gulpfile apunta a la version 0.9.2 no hubo cambio como en package.json

**Comment by fluzzi** [comment]
un dato más, me lo crea bien cuando a tengo nw en la carpeta cache, borro el cuevana "mal creado" y corro npm run build denuevo
ahi funciona.

**Comment by ivantodorovich** [comment]
Cuando mande el PR de `node-webkit-builder` todavía no había publicada en npm una versión estable, estaba todavía en desarrollo, y por eso la dependencia se hizo diréctamente al repositorio.

El problema con eso es que pueden estar haciendo cambios en el repositorio que esté rompiendo nuestro código. Si con el 0.0.2 anda bien, entonces sería bueno definirlo así en nuestras dependencias
