### ISSUE TITLE
npm install - problem

### ISSUE THREAD

**Issue by Bageron** [Cuevana/storm#76]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ 'c:\storm3',
6 verbose install   [ 'peerflix',
6 verbose install     'network-address',
6 verbose install     'request',
6 verbose install     'moment',
6 verbose install     'read-torrent',
6 verbose install     'numeral',
6 verbose install     'i18n',
6 verbose install     'gulp',
6 verbose install     'gulp-inject',
6 verbose install     'gulp-clean',
6 verbose install     'gulp-concat',
6 verbose install     'gulp-less',
6 verbose install     'nodewebkit',
6 verbose install     'node-webkit-builder' ] ]
7 info preinstall Cuevana@0.2.0
8 verbose readDependencies using package.json deps
9 verbose cache add [ 'peerflix@~0.8.3', null ]
10 verbose cache add name=undefined spec="peerflix@~0.8.3" args=["peerflix@~0.8.3",null]
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'peerflix@~0.8.3',
11 verbose parsed url   path: 'peerflix@~0.8.3',
11 verbose parsed url   href: 'peerflix@~0.8.3' }
12 verbose cache add name="peerflix" spec="~0.8.3" args=["peerflix","~0.8.3"]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: '~0.8.3',
13 verbose parsed url   path: '~0.8.3',
13 verbose parsed url   href: '~0.8.3' }
14 verbose addNamed [ 'peerflix', '~0.8.3' ]
15 verbose addNamed [ null, '>=0.8.3-0 <0.9.0-0' ]
16 verbose cache add [ 'network-address@0.0.4', null ]
17 verbose cache add name=undefined spec="network-address@0.0.4" args=["network-address@0.0.4",null]
18 verbose parsed url { protocol: null,
18 verbose parsed url   slashes: null,
18 verbose parsed url   auth: null,
18 verbose parsed url   host: null,
18 verbose parsed url   port: null,
18 verbose parsed url   hostname: null,
18 verbose parsed url   hash: null,
18 verbose parsed url   search: null,
18 verbose parsed url   query: null,
18 verbose parsed url   pathname: 'network-address@0.0.4',
18 verbose parsed url   path: 'network-address@0.0.4',
18 verbose parsed url   href: 'network-address@0.0.4' }
19 verbose cache add name="network-address" spec="0.0.4" args=["network-address","0.0.4"]
20 verbose parsed url { protocol: null,
20 verbose parsed url   slashes: null,
20 verbose parsed url   auth: null,
20 verbose parsed url   host: null,
20 verbose parsed url   port: null,
20 verbose parsed url   hostname: null,
20 verbose parsed url   hash: null,
20 verbose parsed url   search: null,
20 verbose parsed url   query: null,
20 verbose parsed url   pathname: '0.0.4',
20 verbose parsed url   path: '0.0.4',
20 verbose parsed url   href: '0.0.4' }
21 verbose addNamed [ 'network-address', '0.0.4' ]
22 verbose addNamed [ '0.0.4', '0.0.4' ]
23 verbose cache add [ 'request@~2.34.0', null ]
24 verbose cache add name=undefined spec="request@~2.34.0" args=["request@~2.34.0",null]
25 verbose parsed url { protocol: null,
25 verbose parsed url   slashes: null,
25 verbose parsed url   auth: null,
25 verbose parsed url   host: null,
25 verbose parsed url   port: null,
25 verbose parsed url   hostname: null,
25 verbose parsed url   hash: null,
25 verbose parsed url   search: null,
25 verbose parsed url   query: null,
25 verbose parsed url   pathname: 'request@~2.34.0',
25 verbose parsed url   path: 'request@~2.34.0',
25 verbose parsed url   href: 'request@~2.34.0' }
26 verbose cache add name="request" spec="~2.34.0" args=["request","~2.34.0"]
27 verbose parsed url { protocol: null,
27 verbose parsed url   slashes: null,
27 verbose parsed url   auth: null,
27 verbose parsed url   host: null,
27 verbose parsed url   port: null,
27 verbose parsed url   hostname: null,
27 verbose parsed url   hash: null,
27 verbose parsed url   search: null,
27 verbose parsed url   query: null,
27 verbose parsed url   pathname: '~2.34.0',
27 verbose parsed url   path: '~2.34.0',
27 verbose parsed url   href: '~2.34.0' }
28 verbose addNamed [ 'request', '~2.34.0' ]
29 verbose addNamed [ null, '>=2.34.0-0 <2.35.0-0' ]
30 verbose cache add [ 'moment@~2.5.1', null ]
31 verbose cache add name=undefined spec="moment@~2.5.1" args=["moment@~2.5.1",null]
32 verbose parsed url { protocol: null,
32 verbose parsed url   slashes: null,
32 verbose parsed url   auth: null,
32 verbose parsed url   host: null,
32 verbose parsed url   port: null,
32 verbose parsed url   hostname: null,
32 verbose parsed url   hash: null,
32 verbose parsed url   search: null,
32 verbose parsed url   query: null,
32 verbose parsed url   pathname: 'moment@~2.5.1',
32 verbose parsed url   path: 'moment@~2.5.1',
32 verbose parsed url   href: 'moment@~2.5.1' }
33 verbose cache add name="moment" spec="~2.5.1" args=["moment","~2.5.1"]
34 verbose parsed url { protocol: null,
34 verbose parsed url   slashes: null,
34 verbose parsed url   auth: null,
34 verbose parsed url   host: null,
34 verbose parsed url   port: null,
34 verbose parsed url   hostname: null,
34 verbose parsed url   hash: null,
34 verbose parsed url   search: null,
34 verbose parsed url   query: null,
34 verbose parsed url   pathname: '~2.5.1',
34 verbose parsed url   path: '~2.5.1',
34 verbose parsed url   href: '~2.5.1' }
35 verbose addNamed [ 'moment', '~2.5.1' ]
36 verbose addNamed [ null, '>=2.5.1-0 <2.6.0-0' ]
37 verbose cache add [ 'read-torrent@~1.0.0', null ]
38 verbose cache add name=undefined spec="read-torrent@~1.0.0" args=["read-torrent@~1.0.0",null]
39 verbose parsed url { protocol: null,
39 verbose parsed url   slashes: null,
39 verbose parsed url   auth: null,
39 verbose parsed url   host: null,
39 verbose parsed url   port: null,
39 verbose parsed url   hostname: null,
39 verbose parsed url   hash: null,
39 verbose parsed url   search: null,
39 verbose parsed url   query: null,
39 verbose parsed url   pathname: 'read-torrent@~1.0.0',
39 verbose parsed url   path: 'read-torrent@~1.0.0',
39 verbose parsed url   href: 'read-torrent@~1.0.0' }
40 verbose cache add name="read-torrent" spec="~1.0.0" args=["read-torrent","~1.0.0"]
41 verbose parsed url { protocol: null,
41 verbose parsed url   slashes: null,
41 verbose parsed url   auth: null,
41 verbose parsed url   host: null,
41 verbose parsed url   port: null,
41 verbose parsed url   hostname: null,
41 verbose parsed url   hash: null,
41 verbose parsed url   search: null,
41 verbose parsed url   query: null,
41 verbose parsed url   pathname: '~1.0.0',
41 verbose parsed url   path: '~1.0.0',
41 verbose parsed url   href: '~1.0.0' }
42 verbose addNamed [ 'read-torrent', '~1.0.0' ]
43 verbose addNamed [ null, '>=1.0.0-0 <1.1.0-0' ]
44 verbose cache add [ 'numeral@^1.5.3', null ]
45 verbose cache add name=undefined spec="numeral@^1.5.3" args=["numeral@^1.5.3",null]
46 verbose parsed url { protocol: null,
46 verbose parsed url   slashes: null,
46 verbose parsed url   auth: null,
46 verbose parsed url   host: null,
46 verbose parsed url   port: null,
46 verbose parsed url   hostname: null,
46 verbose parsed url   hash: null,
46 verbose parsed url   search: null,
46 verbose parsed url   query: null,
46 verbose parsed url   pathname: 'numeral@^1.5.3',
46 verbose parsed url   path: 'numeral@^1.5.3',
46 verbose parsed url   href: 'numeral@^1.5.3' }
47 verbose cache add name="numeral" spec="^1.5.3" args=["numeral","^1.5.3"]
48 verbose parsed url { protocol: null,
48 verbose parsed url   slashes: null,
48 verbose parsed url   auth: null,
48 verbose parsed url   host: null,
48 verbose parsed url   port: null,
48 verbose parsed url   hostname: null,
48 verbose parsed url   hash: null,
48 verbose parsed url   search: null,
48 verbose parsed url   query: null,
48 verbose parsed url   pathname: '^1.5.3',
48 verbose parsed url   path: '^1.5.3',
48 verbose parsed url   href: '^1.5.3' }
49 verbose addNamed [ 'numeral', '^1.5.3' ]
50 verbose addNamed [ null, '>=1.5.3-0 <2.0.0-0' ]
51 verbose cache add [ 'i18n@~0.4.1', null ]
52 verbose cache add name=undefined spec="i18n@~0.4.1" args=["i18n@~0.4.1",null]
53 verbose parsed url { protocol: null,
53 verbose parsed url   slashes: null,
53 verbose parsed url   auth: null,
53 verbose parsed url   host: null,
53 verbose parsed url   port: null,
53 verbose parsed url   hostname: null,
53 verbose parsed url   hash: null,
53 verbose parsed url   search: null,
53 verbose parsed url   query: null,
53 verbose parsed url   pathname: 'i18n@~0.4.1',
53 verbose parsed url   path: 'i18n@~0.4.1',
53 verbose parsed url   href: 'i18n@~0.4.1' }
54 verbose cache add name="i18n" spec="~0.4.1" args=["i18n","~0.4.1"]
55 verbose parsed url { protocol: null,
55 verbose parsed url   slashes: null,
55 verbose parsed url   auth: null,
55 verbose parsed url   host: null,
55 verbose parsed url   port: null,
55 verbose parsed url   hostname: null,
55 verbose parsed url   hash: null,
55 verbose parsed url   search: null,
55 verbose parsed url   query: null,
55 verbose parsed url   pathname: '~0.4.1',
55 verbose parsed url   path: '~0.4.1',
55 verbose parsed url   href: '~0.4.1' }
56 verbose addNamed [ 'i18n', '~0.4.1' ]
57 verbose addNamed [ null, '>=0.4.1-0 <0.5.0-0' ]
58 verbose cache add [ 'gulp@~3.5.6', null ]
59 verbose cache add name=undefined spec="gulp@~3.5.6" args=["gulp@~3.5.6",null]
60 verbose parsed url { protocol: null,
60 verbose parsed url   slashes: null,
60 verbose parsed url   auth: null,
60 verbose parsed url   host: null,
60 verbose parsed url   port: null,
60 verbose parsed url   hostname: null,
60 verbose parsed url   hash: null,
60 verbose parsed url   search: null,
60 verbose parsed url   query: null,
60 verbose parsed url   pathname: 'gulp@~3.5.6',
60 verbose parsed url   path: 'gulp@~3.5.6',
60 verbose parsed url   href: 'gulp@~3.5.6' }
61 verbose cache add name="gulp" spec="~3.5.6" args=["gulp","~3.5.6"]
62 verbose parsed url { protocol: null,
62 verbose parsed url   slashes: null,
62 verbose parsed url   auth: null,
62 verbose parsed url   host: null,
62 verbose parsed url   port: null,
62 verbose parsed url   hostname: null,
62 verbose parsed url   hash: null,
62 verbose parsed url   search: null,
62 verbose parsed url   query: null,
62 verbose parsed url   pathname: '~3.5.6',
62 verbose parsed url   path: '~3.5.6',
62 verbose parsed url   href: '~3.5.6' }
63 verbose addNamed [ 'gulp', '~3.5.6' ]
64 verbose addNamed [ null, '>=3.5.6-0 <3.6.0-0' ]
65 verbose cache add [ 'gulp-inject@~0.4.1', null ]
66 verbose cache add name=undefined spec="gulp-inject@~0.4.1" args=["gulp-inject@~0.4.1",null]
67 verbose parsed url { protocol: null,
67 verbose parsed url   slashes: null,
67 verbose parsed url   auth: null,
67 verbose parsed url   host: null,
67 verbose parsed url   port: null,
67 verbose parsed url   hostname: null,
67 verbose parsed url   hash: null,
67 verbose parsed url   search: null,
67 verbose parsed url   query: null,
67 verbose parsed url   pathname: 'gulp-inject@~0.4.1',
67 verbose parsed url   path: 'gulp-inject@~0.4.1',
67 verbose parsed url   href: 'gulp-inject@~0.4.1' }
68 verbose cache add name="gulp-inject" spec="~0.4.1" args=["gulp-inject","~0.4.1"]
69 verbose parsed url { protocol: null,
69 verbose parsed url   slashes: null,
69 verbose parsed url   auth: null,
69 verbose parsed url   host: null,
69 verbose parsed url   port: null,
69 verbose parsed url   hostname: null,
69 verbose parsed url   hash: null,
69 verbose parsed url   search: null,
69 verbose parsed url   query: null,
69 verbose parsed url   pathname: '~0.4.1',
69 verbose parsed url   path: '~0.4.1',
69 verbose parsed url   href: '~0.4.1' }
70 verbose addNamed [ 'gulp-inject', '~0.4.1' ]
71 verbose addNamed [ null, '>=0.4.1-0 <0.5.0-0' ]
72 verbose cache add [ 'gulp-clean@~0.2.4', null ]
73 verbose cache add name=undefined spec="gulp-clean@~0.2.4" args=["gulp-clean@~0.2.4",null]
74 verbose parsed url { protocol: null,
74 verbose parsed url   slashes: null,
74 verbose parsed url   auth: null,
74 verbose parsed url   host: null,
74 verbose parsed url   port: null,
74 verbose parsed url   hostname: null,
74 verbose parsed url   hash: null,
74 verbose parsed url   search: null,
74 verbose parsed url   query: null,
74 verbose parsed url   pathname: 'gulp-clean@~0.2.4',
74 verbose parsed url   path: 'gulp-clean@~0.2.4',
74 verbose parsed url   href: 'gulp-clean@~0.2.4' }
75 verbose cache add name="gulp-clean" spec="~0.2.4" args=["gulp-clean","~0.2.4"]
76 verbose parsed url { protocol: null,
76 verbose parsed url   slashes: null,
76 verbose parsed url   auth: null,
76 verbose parsed url   host: null,
76 verbose parsed url   port: null,
76 verbose parsed url   hostname: null,
76 verbose parsed url   hash: null,
76 verbose parsed url   search: null,
76 verbose parsed url   query: null,
76 verbose parsed url   pathname: '~0.2.4',
76 verbose parsed url   path: '~0.2.4',
76 verbose parsed url   href: '~0.2.4' }
77 verbose addNamed [ 'gulp-clean', '~0.2.4' ]
78 verbose addNamed [ null, '>=0.2.4-0 <0.3.0-0' ]
79 verbose cache add [ 'gulp-concat@~2.2.0', null ]
80 verbose cache add name=undefined spec="gulp-concat@~2.2.0" args=["gulp-concat@~2.2.0",null]
81 verbose parsed url { protocol: null,
81 verbose parsed url   slashes: null,
81 verbose parsed url   auth: null,
81 verbose parsed url   host: null,
81 verbose parsed url   port: null,
81 verbose parsed url   hostname: null,
81 verbose parsed url   hash: null,
81 verbose parsed url   search: null,
81 verbose parsed url   query: null,
81 verbose parsed url   pathname: 'gulp-concat@~2.2.0',
81 verbose parsed url   path: 'gulp-concat@~2.2.0',
81 verbose parsed url   href: 'gulp-concat@~2.2.0' }
82 verbose cache add name="gulp-concat" spec="~2.2.0" args=["gulp-concat","~2.2.0"]
83 verbose parsed url { protocol: null,
83 verbose parsed url   slashes: null,
83 verbose parsed url   auth: null,
83 verbose parsed url   host: null,
83 verbose parsed url   port: null,
83 verbose parsed url   hostname: null,
83 verbose parsed url   hash: null,
83 verbose parsed url   search: null,
83 verbose parsed url   query: null,
83 verbose parsed url   pathname: '~2.2.0',
83 verbose parsed url   path: '~2.2.0',
83 verbose parsed url   href: '~2.2.0' }
84 verbose addNamed [ 'gulp-concat', '~2.2.0' ]
85 verbose addNamed [ null, '>=2.2.0-0 <2.3.0-0' ]
86 verbose cache add [ 'gulp-less@~1.2.3', null ]
87 verbose cache add name=undefined spec="gulp-less@~1.2.3" args=["gulp-less@~1.2.3",null]
88 verbose parsed url { protocol: null,
88 verbose parsed url   slashes: null,
88 verbose parsed url   auth: null,
88 verbose parsed url   host: null,
88 verbose parsed url   port: null,
88 verbose parsed url   hostname: null,
88 verbose parsed url   hash: null,
88 verbose parsed url   search: null,
88 verbose parsed url   query: null,
88 verbose parsed url   pathname: 'gulp-less@~1.2.3',
88 verbose parsed url   path: 'gulp-less@~1.2.3',
88 verbose parsed url   href: 'gulp-less@~1.2.3' }
89 verbose cache add name="gulp-less" spec="~1.2.3" args=["gulp-less","~1.2.3"]
90 verbose parsed url { protocol: null,
90 verbose parsed url   slashes: null,
90 verbose parsed url   auth: null,
90 verbose parsed url   host: null,
90 verbose parsed url   port: null,
90 verbose parsed url   hostname: null,
90 verbose parsed url   hash: null,
90 verbose parsed url   search: null,
90 verbose parsed url   query: null,
90 verbose parsed url   pathname: '~1.2.3',
90 verbose parsed url   path: '~1.2.3',
90 verbose parsed url   href: '~1.2.3' }
91 verbose addNamed [ 'gulp-less', '~1.2.3' ]
92 verbose addNamed [ null, '>=1.2.3-0 <1.3.0-0' ]
93 verbose cache add [ 'nodewebkit@0.9.2-4', null ]
94 verbose cache add name=undefined spec="nodewebkit@0.9.2-4" args=["nodewebkit@0.9.2-4",null]
95 verbose parsed url { protocol: null,
95 verbose parsed url   slashes: null,
95 verbose parsed url   auth: null,
95 verbose parsed url   host: null,
95 verbose parsed url   port: null,
95 verbose parsed url   hostname: null,
95 verbose parsed url   hash: null,
95 verbose parsed url   search: null,
95 verbose parsed url   query: null,
95 verbose parsed url   pathname: 'nodewebkit@0.9.2-4',
95 verbose parsed url   path: 'nodewebkit@0.9.2-4',
95 verbose parsed url   href: 'nodewebkit@0.9.2-4' }
96 verbose cache add name="nodewebkit" spec="0.9.2-4" args=["nodewebkit","0.9.2-4"]
97 verbose parsed url { protocol: null,
97 verbose parsed url   slashes: null,
97 verbose parsed url   auth: null,
97 verbose parsed url   host: null,
97 verbose parsed url   port: null,
97 verbose parsed url   hostname: null,
97 verbose parsed url   hash: null,
97 verbose parsed url   search: null,
97 verbose parsed url   query: null,
97 verbose parsed url   pathname: '0.9.2-4',
97 verbose parsed url   path: '0.9.2-4',
97 verbose parsed url   href: '0.9.2-4' }
98 verbose addNamed [ 'nodewebkit', '0.9.2-4' ]
99 verbose addNamed [ '0.9.2-4', '0.9.2-4' ]
100 verbose cache add [ 'node-webkit-builder@git://github.com/mllrsohn/node-webkit-builder',
100 verbose cache add   null ]
101 verbose cache add name=undefined spec="node-webkit-builder@git://github.com/mllrsohn/node-webkit-builder" args=["node-webkit-builder@git://github.com/mllrsohn/node-webkit-builder",null]
102 verbose parsed url { protocol: null,
102 verbose parsed url   slashes: null,
102 verbose parsed url   auth: null,
102 verbose parsed url   host: null,
102 verbose parsed url   port: null,
102 verbose parsed url   hostname: null,
102 verbose parsed url   hash: null,
102 verbose parsed url   search: null,
102 verbose parsed url   query: null,
102 verbose parsed url   pathname: 'node-webkit-builder@git://github.com/mllrsohn/node-webkit-builder',
102 verbose parsed url   path: 'node-webkit-builder@git://github.com/mllrsohn/node-webkit-builder',
102 verbose parsed url   href: 'node-webkit-builder@git://github.com/mllrsohn/node-webkit-builder' }
103 silly lockFile 7a0ceee8-peerflix-0-8-3 peerflix@~0.8.3
104 verbose lock peerflix@~0.8.3 C:\Users\Unknow\AppData\Roaming\npm-cache\7a0ceee8-peerflix-0-8-3.lock
105 silly lockFile 5922a0db-network-address-0-0-4 network-address@0.0.4
106 verbose lock network-address@0.0.4 C:\Users\Unknow\AppData\Roaming\npm-cache\5922a0db-network-address-0-0-4.lock
107 silly lockFile 1fb009df-request-2-34-0 request@~2.34.0
108 verbose lock request@~2.34.0 C:\Users\Unknow\AppData\Roaming\npm-cache\1fb009df-request-2-34-0.lock
109 silly lockFile 10e95e81-moment-2-5-1 moment@~2.5.1
110 verbose lock moment@~2.5.1 C:\Users\Unknow\AppData\Roaming\npm-cache\10e95e81-moment-2-5-1.lock
111 silly lockFile 7029dd10-read-torrent-1-0-0 read-torrent@~1.0.0
112 verbose lock read-torrent@~1.0.0 C:\Users\Unknow\AppData\Roaming\npm-cache\7029dd10-read-torrent-1-0-0.lock
113 silly lockFile a2c69d4a-numeral-1-5-3 numeral@^1.5.3
114 verbose lock numeral@^1.5.3 C:\Users\Unknow\AppData\Roaming\npm-cache\a2c69d4a-numeral-1-5-3.lock
115 silly lockFile 57f41367-i18n-0-4-1 i18n@~0.4.1
116 verbose lock i18n@~0.4.1 C:\Users\Unknow\AppData\Roaming\npm-cache\57f41367-i18n-0-4-1.lock
117 silly lockFile 1c26bd9a-gulp-3-5-6 gulp@~3.5.6
118 verbose lock gulp@~3.5.6 C:\Users\Unknow\AppData\Roaming\npm-cache\1c26bd9a-gulp-3-5-6.lock
119 silly lockFile a4656cdf-gulp-inject-0-4-1 gulp-inject@~0.4.1
120 verbose lock gulp-inject@~0.4.1 C:\Users\Unknow\AppData\Roaming\npm-cache\a4656cdf-gulp-inject-0-4-1.lock
121 silly lockFile 0031adfc-gulp-clean-0-2-4 gulp-clean@~0.2.4
122 verbose lock gulp-clean@~0.2.4 C:\Users\Unknow\AppData\Roaming\npm-cache\0031adfc-gulp-clean-0-2-4.lock
123 silly lockFile 6fc80744-gulp-concat-2-2-0 gulp-concat@~2.2.0
124 verbose lock gulp-concat@~2.2.0 C:\Users\Unknow\AppData\Roaming\npm-cache\6fc80744-gulp-concat-2-2-0.lock
125 silly lockFile cd9cb1ab-gulp-less-1-2-3 gulp-less@~1.2.3
126 verbose lock gulp-less@~1.2.3 C:\Users\Unknow\AppData\Roaming\npm-cache\cd9cb1ab-gulp-less-1-2-3.lock
127 silly lockFile e62c3145-nodewebkit-0-9-2-4 nodewebkit@0.9.2-4
128 verbose lock nodewebkit@0.9.2-4 C:\Users\Unknow\AppData\Roaming\npm-cache\e62c3145-nodewebkit-0-9-2-4.lock
129 verbose cache add name="node-webkit-builder" spec="git://github.com/mllrsohn/node-webkit-builder" args=["node-webkit-builder","git://github.com/mllrsohn/node-webkit-builder"]
130 verbose parsed url { protocol: 'git:',
130 verbose parsed url   slashes: true,
130 verbose parsed url   auth: null,
130 verbose parsed url   host: 'github.com',
130 verbose parsed url   port: null,
130 verbose parsed url   hostname: 'github.com',
130 verbose parsed url   hash: null,
130 verbose parsed url   search: null,
130 verbose parsed url   query: null,
130 verbose parsed url   pathname: '/mllrsohn/node-webkit-builder',
130 verbose parsed url   path: '/mllrsohn/node-webkit-builder',
130 verbose parsed url   href: 'git://github.com/mllrsohn/node-webkit-builder' }
131 silly lockFile 5202aaad-com-mllrsohn-node-webkit-builder git://github.com/mllrsohn/node-webkit-builder
132 verbose lock git://github.com/mllrsohn/node-webkit-builder C:\Users\Unknow\AppData\Roaming\npm-cache\5202aaad-com-mllrsohn-node-webkit-builder.lock
133 silly addNameRange { name: 'request',
133 silly addNameRange   range: '>=2.34.0-0 <2.35.0-0',
133 silly addNameRange   hasData: false }
134 silly addNameRange { name: 'moment', range: '>=2.5.1-0 <2.6.0-0', hasData: false }
135 silly addNameRange { name: 'read-torrent',
135 silly addNameRange   range: '>=1.0.0-0 <1.1.0-0',
135 silly addNameRange   hasData: false }
136 silly addNameRange { name: 'numeral', range: '>=1.5.3-0 <2.0.0-0', hasData: false }
137 silly addNameRange { name: 'i18n', range: '>=0.4.1-0 <0.5.0-0', hasData: false }
138 silly addNameRange { name: 'gulp', range: '>=3.5.6-0 <3.6.0-0', hasData: false }
139 silly addNameRange { name: 'gulp-inject',
139 silly addNameRange   range: '>=0.4.1-0 <0.5.0-0',
139 silly addNameRange   hasData: false }
140 silly addNameRange { name: 'gulp-clean',
140 silly addNameRange   range: '>=0.2.4-0 <0.3.0-0',
140 silly addNameRange   hasData: false }
141 silly addNameRange { name: 'gulp-concat',
141 silly addNameRange   range: '>=2.2.0-0 <2.3.0-0',
141 silly addNameRange   hasData: false }
142 silly addNameRange { name: 'peerflix', range: '>=0.8.3-0 <0.9.0-0', hasData: false }
143 verbose addRemoteGit [ 'git://github.com/mllrsohn/node-webkit-builder', 'master' ]
144 silly addNameRange { name: 'gulp-less',
144 silly addNameRange   range: '>=1.2.3-0 <1.3.0-0',
144 silly addNameRange   hasData: false }
145 verbose url raw request
146 verbose url resolving [ 'https://registry.npmjs.org/', './request' ]
147 verbose url resolved https://registry.npmjs.org/request
148 info trying registry request attempt 1 at 01:42:28
149 verbose etag "1KRQ86R9URFA3N1AWBN33N2KW"
150 http GET https://registry.npmjs.org/request
151 verbose url raw moment
152 verbose url resolving [ 'https://registry.npmjs.org/', './moment' ]
153 verbose url resolved https://registry.npmjs.org/moment
154 info trying registry request attempt 1 at 01:42:28
155 verbose etag "E6JJ3P93B8ON3P03KC77317XH"
156 http GET https://registry.npmjs.org/moment
157 verbose url raw read-torrent
158 verbose url resolving [ 'https://registry.npmjs.org/', './read-torrent' ]
159 verbose url resolved https://registry.npmjs.org/read-torrent
160 info trying registry request attempt 1 at 01:42:28
161 verbose etag "BDA218UBFB6JAFUSM22V850EH"
162 http GET https://registry.npmjs.org/read-torrent
163 verbose url raw numeral
164 verbose url resolving [ 'https://registry.npmjs.org/', './numeral' ]
165 verbose url resolved https://registry.npmjs.org/numeral
166 info trying registry request attempt 1 at 01:42:28
167 verbose etag "5ZK1VB1MLC76XM89LRSBGV4E2"
168 http GET https://registry.npmjs.org/numeral
169 verbose url raw i18n
170 verbose url resolving [ 'https://registry.npmjs.org/', './i18n' ]
171 verbose url resolved https://registry.npmjs.org/i18n
172 info trying registry request attempt 1 at 01:42:28
173 verbose etag "EU2PB44ITDDJL2K4M3CHO7WZE"
174 http GET https://registry.npmjs.org/i18n
175 verbose url raw gulp
176 verbose url resolving [ 'https://registry.npmjs.org/', './gulp' ]
177 verbose url resolved https://registry.npmjs.org/gulp
178 info trying registry request attempt 1 at 01:42:28
179 verbose etag "6CX8EXD69U1DA3D0GWVKZLDQ8"
180 http GET https://registry.npmjs.org/gulp
181 verbose url raw gulp-inject
182 verbose url resolving [ 'https://registry.npmjs.org/', './gulp-inject' ]
183 verbose url resolved https://registry.npmjs.org/gulp-inject
184 info trying registry request attempt 1 at 01:42:28
185 verbose etag "6YNDSZQJS34131X1NNFQXZHQA"
186 http GET https://registry.npmjs.org/gulp-inject
187 verbose url raw gulp-clean
188 verbose url resolving [ 'https://registry.npmjs.org/', './gulp-clean' ]
189 verbose url resolved https://registry.npmjs.org/gulp-clean
190 info trying registry request attempt 1 at 01:42:28
191 verbose etag "74GP0VTS4W942JO5TLLY92UKX"
192 http GET https://registry.npmjs.org/gulp-clean
193 verbose url raw gulp-concat
194 verbose url resolving [ 'https://registry.npmjs.org/', './gulp-concat' ]
195 verbose url resolved https://registry.npmjs.org/gulp-concat
196 info trying registry request attempt 1 at 01:42:28
197 verbose etag "9AF2I6EFT5DXITW3TLT599DUU"
198 http GET https://registry.npmjs.org/gulp-concat
199 verbose url raw nodewebkit/0.9.2-4
200 verbose url resolving [ 'https://registry.npmjs.org/', './nodewebkit/0.9.2-4' ]
201 verbose url resolved https://registry.npmjs.org/nodewebkit/0.9.2-4
202 info trying registry request attempt 1 at 01:42:28
203 verbose etag "1CL7RAYSB13VHNTBWRMP7IP8E"
204 http GET https://registry.npmjs.org/nodewebkit/0.9.2-4
205 verbose url raw peerflix
206 verbose url resolving [ 'https://registry.npmjs.org/', './peerflix' ]
207 verbose url resolved https://registry.npmjs.org/peerflix
208 info trying registry request attempt 1 at 01:42:28
209 verbose etag "44R2GON2BV4QIE0HNXJ7N5VO5"
210 http GET https://registry.npmjs.org/peerflix
211 verbose url raw network-address/0.0.4
212 verbose url resolving [ 'https://registry.npmjs.org/', './network-address/0.0.4' ]
213 verbose url resolved https://registry.npmjs.org/network-address/0.0.4
214 info trying registry request attempt 1 at 01:42:28
215 verbose etag "6CF4S1651YZUNC5LDMD1QZSO3"
216 http GET https://registry.npmjs.org/network-address/0.0.4
217 verbose url raw gulp-less
218 verbose url resolving [ 'https://registry.npmjs.org/', './gulp-less' ]
219 verbose url resolved https://registry.npmjs.org/gulp-less
220 info trying registry request attempt 1 at 01:42:28
221 verbose etag "CJWF7M6WEE6MEQ1A1ZRW1OB7T"
222 http GET https://registry.npmjs.org/gulp-less
223 silly lockFile 5202aaad-com-mllrsohn-node-webkit-builder git://github.com/mllrsohn/node-webkit-builder
224 silly lockFile 5202aaad-com-mllrsohn-node-webkit-builder git://github.com/mllrsohn/node-webkit-builder
225 error not found: git
226 error Failed using git.
226 error This is most likely not a problem with npm itself.
226 error Please check if you have git installed and in your PATH.
227 error System Windows_NT 6.1.7601
228 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
229 error cwd c:\storm3
230 error node -v v0.10.26
231 error npm -v 1.4.3
232 error code ENOGIT
233 verbose exit [ 1, true ]

**Comment by fluzzi** [comment]
ya esta resuelto esto, proba denuevo
