### ISSUE TITLE
Error con 'npm run build' en Linux 64 bits

### ISSUE THREAD

**Issue by ghost** [Cuevana/storm#78]
Por alguna razón al usar 'npm run build' en una distro Linux de 64 bits node-webkit-builder descarga y usa la versión de 32 bits de nodewebkit. Todo termina exitosamente pero el binario que genera no se ejecuta. Aquí dejo la salida:

<blockquote>> Cuevana@0.2.0 build /home/equipo/Escritorio/storm-master
> gulp build

[gulp] Using gulpfile /home/equipo/Escritorio/storm-master/gulpfile.js<br/>
[gulp] Starting 'styles'...<br/>
[gulp] Finished 'styles' after 204 ms<br/>
[gulp] Starting 'injecthtml:index'...<br/>
[gulp] Starting 'injecthtml:player'...<br/>
[gulp] Finished 'injecthtml:index' after 25 ms<br/>
[gulp] Finished 'injecthtml:player' after 21 ms<br/>
[gulp] Starting 'injecthtml'...<br/>
[gulp] Finished 'injecthtml' after 7.9 μs<br/>
[gulp] Starting 'compile'...<br/>
[gulp] Finished 'compile' after 7.62 μs<br/>
[gulp] Starting 'build'...<br/>
Using v0.9.2<br/>
Create cache folder in /home/equipo/Escritorio/storm-master/build/cache/0.9.2<br/>
Downloading: http://dl.node-webkit.org/v0.9.2/node-webkit-v0.9.2-linux-ia32.tar.gz<br/>
Create release folder in /home/equipo/Escritorio/storm-master/build/Cuevana/linux64<br/>
[gulp] Finished 'build' after 8.97 min</blockquote>

<hr/>

Descargando manualmente el archivo 'http://dl.node-webkit.org/v0.9.2/node-webkit-v0.9.2-linux-x64.tar.gz' y reemplazando los archivos de la carpeta cache por estos, al ejecutar nuevamente 'npm run build' el binario que genera funciona correctamente. 

<hr/>

Al ejecutar 'npm run build-all' descarga correctamente nodewebkit para todas las plataformas y genera los binarios, pero curiosamente el que me funciona es el de Linux 32 bits, el de 64 bits no se ejecuta. Esto me sale:

<blockquote>./nw: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory</blockquote>

**Comment by ivantodorovich** [comment]
Hmmm.. debe ser un problema de `node-webkit-builder`, confundiendo las dos plataformas. ahora lo veo

**Comment by ivantodorovich** [comment]
Fix: https://github.com/mllrsohn/node-webkit-builder/pull/10
