### ISSUE TITLE
English usage

### ISSUE THREAD

**Issue by ricl** [Cuevana/storm#79]
When installed (with the installer from http://www.cuevana.tv/) it defaults to the Spanish language with no apparent option to switch to English.

**Comment by fluzzi** [comment]
English is already supported on github version but you have to build the app yourself. for this you have to install nodejs, and then follow the instructions on readme file. If not you'll have to wait to next update.

**Comment by ricl** [comment]
Ok Tks. Node.js build is broken on my PC at present do I will just have to wait.

**Comment by ghost** [comment]
May i ask when we can espect Cuevana-Storm to be relesed with option for English UI.. I realy look forward to see this happend but have no idea if there is maybe some info outhere about time frame in wich we can espected new relese.. Any Info will be much appreciated..
Regards

**Comment by Zer0t3ch** [comment]
I'm interested in this as well. And if they need any help with the localization, I would be happy to help.

**Comment by Cuevana** [comment]
There is english support. It should detect your OS language.

**Comment by Draxler** [comment]
@Cuevana
it doesn't detect anything i installed (new version) and reinstalled 3 times already with the same outcome, that is, i get Spanish lang only, every time..

**Comment by Cuevana** [comment]
English version is supported, but there is a bug in the latest version of node-webkit in Windows, that fails to detect OS language. We'll be updating as soon as a fix is available.
We will be adding language selection in Settings as well so you can force your selection.
