### ISSUE TITLE
Actualización de nuevas peliculas nula

### ISSUE THREAD

**Issue by DarwinJ94** [Cuevana/storm#81]
¿Por qué no actualizan las peliculas de la aplicación? Deberian ampliar la varidad de peliculas que hay y añadir nuevas... no he oido nada sobre actualización de la aplicación tampoco. La unica opción adicional que tengo es Popcorn Time y no me corre bien, reproduce totalmente lagueado cosa que en Cuevana Storm no me sucede para nada y por eso la prefiero mil veces. Deberian mantener la libreria de peliculas actualizada. Si esto no va aqui o no aporta nada, disculparme.

**Comment by pramirez** [comment]
no se como esta estructurado el sistema internamente pero creo que deberían buscar la forma de "centrar" la data para solo preocuparse de actualizar un lugar y que ambos ( pagina web y app ) sean actualizado.

**Comment by ivantodorovich** [comment]
Mm no creo que este desincronizado con la web. Creo que @darwinj94 se refiere a que no se cargan nuevas peliculas a cuevana.

**Comment by Foxito** [comment]
El tema es que al usar una api propia, no tenemos la mas minima posibilidad de elegir, y siempre vamos a depender de lo que cuevana agregue a su base de datos, o sea, si un dia por X motivo dejan de actualizar las peliculas, se acabo storm. 

Habria que pensar en otra solucion, no digo una api propia, porque seguramente el usuario promedio solo quiere ver pelis cargadas, no hostear una api y actualizarla, pero seria interesante desarrolar todas las areas del proyecto de manera abierta para que otros tengan posibilidad de crear sus versiones, por ahi alguien quiere hacer sobre cine retro, o chino, y seria una opcion interesante, al menos para un determinado grupo de gente.

**Comment by ivantodorovich** [comment]
Creo que @Cuevana es, en teoría, una página donde sus usuarios agregan contenido. En la práctica es distinto.. pero qué pasaría si le damos a los usuarios ese poder? 

Desde la misma app, los usuarios podrían ingresar películas nuevas, corregir torrents muertos, agregar los subtítulos.. etc. Los "moderadores" pasarían de ser la única fuente de contenido a ser más que nada evaluadores/catalogadores.

El contenido "no evaluado" o "no verificado" por un moderador debería ser filtrable, y oculto por default. Activable bajo cierta preferencia, advirtiéndo de los posibles problemas que pueda causar (ej: darle play a "Frozen" y que en realidad se abra una porno -- caso extremo, pero puede pasar)

Cada película podría tener no solo 2 fuentes (720 o 1080) sino muchas, ilimitadas, para cada resolución. Sería necesario para que no se "mezclen" los subtítulos.. ya que cada sub debería estar vinculado a la fuente y no a la resolucion (ej: "LOL", "2HD", etc..)

**Comment by Foxito** [comment]
@ivantodorovich tenes razon, me parece que la clave en todos los casos es la moderacion, esta mas que probado que cuando algo se vuelve popular, la automoderacion no funciona, siempre van a aparecer los 20 o 30 trolls que metan su video que nadie quiere ver bajo el nombre de la ultima peli taquillera, a eso sumale porno y spam como bien dijiste.

Respecto a la cantidad de formatos, tambien se volveria super complicado tenes y controlar peliculas en la mayoria de los formatos, me parece que 720 y 1080 es mas que suficiente, con buenos subtitulos que eso noto que ahora esta fallando un poco. Ejemplo: Yo termine de ver la 2da temporada de Grimm, y cada episodio empieza con una frase escrita que hace referencia a la historia que te van a contar, pero es solo texto, sin audio, asi que en muchos capitulos no esta traducido, son pequeños detalles pero a mi personalmente me parece mejor 2 formatos con buenos subtitulos que 20 con todos subtitulos de medio pelo o errores aunque sean menores. 

Para agregar respecto a los formatos, algo que no me gustaria ver es camrips, pero bueno, yo si quiero una peli y esta en camrip, espero a que salga en otro formato, habra a quien no le moleste (porque no creo q les guste) que sea una filmacion del cine con sonido ambiente y ver un peluca que se levanta en medio de la funcion para ir al baño.

Gustos son gustos dijo una vieja...
