### ISSUE TITLE
osx: video/system freeze

### ISSUE THREAD

**Issue by axcoro** [Cuevana/storm#85]
OS: Maverics 10.9.2

Pasos para reprodur el bug:

> Inicia el video, hago full screen la app desde las flechitas que estan en la ventana (arriba a la derecha, seria el "fullscreen nativo"), luego desde el player, hago click en las fechitas para ir a full screen (abajo a la derecha, en los controles del video)

Resultado:

> Se congela el video (y toda la interfaz en gral), pero se sigue ejecutando por detras, si hago clic, se hace play/pause x ejemplo, pero no responde a nigun otro input, al menos visualmente..

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
