### ISSUE TITLE
Está caído

### ISSUE THREAD

**Issue by juanvisbal** [Cuevana/storm#87]
Algo pasó con Cuevana. El portal web está offline, Storm no carga nada, y el link de descarga en Mega lo quitaron.

**Comment by Foxito** [comment]
A mi desde ayer a la tarde/noche que no me cargaba pero ahora parece que volvio a funcionar.

**Comment by Foxito** [comment]
Otra vez no anda la app, y tambien como dijiste vos esta caida la pagina y el archivo en mega fue eliminado... estaria bueno un comentario oficial.
