### ISSUE TITLE
Desinstalar / player en negro no parece ser ffmpegsumo

### ISSUE THREAD

**Issue by Foxito** [Cuevana/storm#89]
No es un problema de la app en si, pero quizas sea util al menos para quienes quieren usar la app sin el .exe compilado.

La sugerencia es agregarle alguna forma simple de "desinstalarla", tipo "npm uninstall", como ya hizo @ivantodorovich para el install y el start.

Recuerdo haber leido hace un tiempo unos mensajes aca mismo, sobre cierto problema en la app donde se sugeria eliminar la cache para ver si se solucionaba. El tema es que ahora tengo un problema, que literalmente de la noche a la mañana, dejo de funcionarme la app, abre lo mas bien, elijo lo que quiero ver, pero cuando abre el player, se queda en negro como cuando tenia problemas con el ffmpegsumo. Intente eliminando el contenido de la carpeta npm-cache en los dos usuarios con los que ejecuto la app, y sigue abriendo sin necesidad de darle "npm install", y el problema sigue sucediendo, asi que no estoy seguro si deberia eliminar algo mas, por lo pronto el problema sigue y sigo sin poder usar la app. Incluso volvi a bajar el archivo ffmpegsumo de aca por las dudas y no se soluciona. 

Saludos

**Comment by ivantodorovich** [comment]
El `npm install` es parte de npm, instala las dependencias leyendo el `package.json`. Lo que le agregué yo es un script para que, cuando termine de instalar las dependencias, copie el ffmpegsumo correspondiente a la carpeta de nodewebkit - y además compilar less y demas tareas de gulp.

`npm start` es basicamente un acceso directo a `nodewebkit . --debug`. 
Si no existe un nodewebkit local (ie: por falta de npm install) intenta utilizar uno global.. esto no es buscado, es fallback de npm. No debería ser un problema, pero por las dudas asegurate de que se te esté ejecutando la versión correcta de nodewebkit. La única con el ffmpegsumo correcto es la que está dentro de node_modules.

Habiendo dicho eso, a que te referís con uninstall? Borrar configuraciones y archivos temporales?

**Comment by Foxito** [comment]
Con uninstall me referia a eliminar todo lo que se hubiese instalado al ejecutar "npm install", para tener que instalarlo nuevamente. Era la opcion mas simple y sencilla que se me habia ocurrido, dado que como dije, a la noche termine de ver una peli, y al otro dia cuando lo volvi a abrir, ya no funcionaba. Por eso elimine la carpeta npm-cache en los dos usuarios de esta notebook y archivos temporales usando el liberador de espacio, y la app seguia abriendo sin necesidad de volver a ejecutar "npm install", y seguia sin funcionar. Asi que supuse que por ahi habria archivos en algun otro lado que yo no supiera, de ahi la sugerencia de agregarle alguna forma simple de eliminar todo lo instalado.

Ahora bien, hasta ultima hora de la noche, siguio igual, abriese lo que abriese, quedaba en 00:00:00 y pantalla negra. Recien me levante, volvi a darle "npm start", volvi a abrir el mismo capitulo de Da Vinci's Demons que habia intentado alguna de las veces ayer y salio andando, sin que durante la noche nadie hubiese tocado la notebook ni hubiese hecho por si sola ningun tipo de actualizacion ni nada.

**Comment by nicolasraffaele** [comment]
yo tengo el mismo problema la verdad que busque y para mi viene por el ffmpegsumo.dll porque la verdad que no encuentro el error... y al ser como decis aparecen fuentes y descarga a veces se queda en negro a veces corre unos segundos y muere, no encuentro de donde puede venir ese error pero bue no hay mucha ayuda con el codigo en general solo unos pocos hicieron algo y no es muy popular el proyecto por lo que veo.

**Comment by Foxito** [comment]
Realmente no se si es el mismo problema, porque yo tuve el problema ese de que quedaba en negro, solamente 2 veces; la primera, cuando por primera vez trate de usar la app bajandola de mega, y me dijeron que era por el ffmpegsumo, y que bajara el zip de aca y lo ejecutara, y desde ahi no tuve mas problemas hasta la segunda vez, que fue cuando abri este issue, y creeria que no fue un problema del ffmpegsumo, ya que lo cambie, lo reemplace por una diferente, lo reemplace por una copia nueva del que deberia ir, y nada resulto, recien al otro dia salio andando sola, asi que me inclinaria por pensar que fue un problema del lado de cuevana, ya que se soluciono solo como paso con los subtitulos con simbolo de interrogacion, y tambien con eso de que estaba caido, mas hace un par de dias, tambian hubo un error que mostraba solo 10 series, y al otro dia volvio a mostrar todas como siempre.

Lo otro que se me ocurre, pero no deberia suceder que pasara alguna veces si y otras no, es que se llenara la particion donde te guarda los temporales, a mi me paso esto una vez, de pronto un capitulo de una serie, se cortaba a los pocos minutos y no pasaba de ahi, y vi que el disco donde me guardaba los temporales estaba lleno, despues de liberar espacio, se soluciono, asi que ahora cada tanto libero para evitar ese problema y listo, no volvio a pasar.

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Sigue los pasos en el README. Gracias.
