### ISSUE TITLE
Subtitulo con símbolos 

### ISSUE THREAD

**Issue by fluzzi** [Cuevana/storm#90]
Desde hace unos días todos los acentos, signos de pregunta, etc aparecen coml símbolos de pregunta 

Le pasa a alguien mas?

**Comment by afharo** [comment]
Sí, a mí también me pasa.
Seguramente tendrá que ver con la codificación del texto (uno estará en UTF-8 y el otro en ISO-8859-1)

**Comment by Foxito** [comment]
A mi me pasaba lo mismo, pero ya esta solucionado, se ve que en la api habian cambiado algo del tema de la codificacion.

**Comment by nicolasraffaele** [comment]
es por la razon que decia afharo y se ve que ya lo solucionaron, igual toy teniendo todo tipo de problemas con la app comienza a reproducir y se frena, a veces ni comienza, me fijo y hay fuentes y demas, la verdad que no se que anda pasando vi el codigo y no me parecio ver nada mal, el tema es el ffmpegsumo.dll debe tener algo mal y ya probe la version que viene con cuevana y la oficial, para colmo a veces pasa a veces no... es raro

**Comment by Cuevana** [comment]
Pedimos disculpas, tuvimos problemas con los servidores, hicimos una migración y olvidamos setear los encoding para servir los subtítulos. A todos ya se les ven correctamente?

**Comment by nicolasraffaele** [comment]
No pasa nada! estamos acá para ayudar e informar bugs no para quejarnos. Todos buscamos el mismo y es que Cuevana Storm mejore día a día!
Si ya se ven correctamente!

**Comment by afharo** [comment]
Esta tarde lo he probado y seguía mostrando símbolos raros...

Alejandro.

**Comment by tinchokaynar** [comment]
los subtitulos sigen con simbolos. 
Saludos

**Comment by iaserrat** [comment]
Subtitulos siguen reemplazando acentos o ñ con símbolos.

**Comment by ajatib** [comment]
Los simbolos siguen ahi y de paso, hay algun problema con los subtitulos?
hay series q tardan semanas en aparecerles el subtitulo (no series q nadie
ve, series como The Big Bang y otras)
Slds

El 20 de mayo de 2014, 15:22, Ismael Serratos
notifications@github.comescribió:

> Subtitulos siguen reemplazando acentos o ñ con símbolos.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cuevana/storm/issues/90#issuecomment-43664007
> .

## 

Alejandro Jatib

**Comment by DrkyCrzy** [comment]
Aún siguen los símbolos.. Se puede solucionar de forma manual ?o es problema directo de los server de los subs?? Me gustaría colaborar

**Comment by hernyds** [comment]
Me pasa exactamente lo mismo. Estaria bueno que avisen si se puede solucionar de forma manual o cuando estaria solucionado esto! Gracias!

**Comment by kevindevm** [comment]
siguen sin funcionar los subtitulos. aparecen con símbolos, tampoco anda el buscador no se puede buscar una película.
estaría bueno que se puedan agregar subitulos externos a una reproduccion 
estaria bueno tmb un menu con opciones, tmb que muestre en que version este

**Comment by kumanosuki** [comment]
Igual me pasa, los subtitulos no se ven bien. acentos , tildes y caracteresdel spanish no se ven.

**Comment by Cuevana** [comment]
Estamos trabajando en una actaulización que solucione esto. Disculpas.

**Comment by kevindevm** [comment]
y nos van a notificar cuando este la actualización o se descarga sola?

**Comment by juanmacio** [comment]
@kevindevm, la aplicación te notifica cuando hay una actualización disponible.

**Comment by ghost** [comment]
La aplicacion la baje hoy y sigo viendo los subtitulos mal. Win7 + English.

Tambien cada tanto se cuelga el video y hay que volver a abrirlo.

**Comment by kumanosuki** [comment]
Los sbtitulos de las series se ven bien, pero los de  las pelis todavia salen con signos raros.

**Comment by adrixvoid** [comment]
El encoding lo sigo viendo mal, también tengo Win7 versión inglés.

**Comment by fastcodecoq** [comment]
Al descargar directamente el .srt desde subs.cuevana..., luego al abrirlo me dice que no tiene una codificación UTF-8 válida, por lo que se puede concluir que el servidor no esta entregando el archivo con la codificación correcta. Si selecciono codificación ISO-8859-14 para abrir el .srt, los subtitulos se muestran con todos los acentos, de forma correcta. Estuve intentando setear este charset en player.html, pero aún estoy experimentando en el tema, espero solucionarlo, pero creo que es muy complicado hacerlo sin tener acceso al archivo que sirve los .srt, que es de donde probablemente se origina el problema.

**Comment by lcnvdl** [comment]
Tengo problemas con Memento (2000) aparecen símbolos raros en vez de acentos.

**Comment by MauroJC** [comment]
Sigo teniendo problemas con la mayor parte de las series/peliculas, me da como loading los subtitulos en español, como puedo solucionarlo? Saludos!!

**Comment by Cuevana** [comment]
Esto debería estar solucionado. Disculpen, costó más de lo que imaginábamos. Puede que tarde en actualizarse los cambios para algunos, pero en las próximas horas debería estar resuelto por completo.

**Comment by iaserrat** [comment]
Sólo por curiosidad, ¿Cuál era el problema?

**Comment by Cuevana** [comment]
@iaserrat Hicimos una migracion completa de servidores y los nuevos al ser almacenamiento en la nube, no podíamos controlar el Content-Type de los requests para enviar el encoding apropiado. Ya seteamos el entorno adecuado.

**Comment by ghost** [comment]
Deberíamos reinstalar alguna nueva version o se soluciona automaticamente? Gracias.

**Comment by pete16es** [comment]
Tengo la misma duda de @kikefas, hay que reinstalar algo, aun no se soluciona.

**Comment by Cuevana** [comment]
Ya está solucionado pero algunos subtitulos que hayan cargado previamente pueden quedar en la caché de la app. Pueden borrar la caché (desde la consola del inspector) o eliminar y reinstalar la app.

**Comment by SepaEsteves** [comment]
Eliminé y reinstalé la app y con la película que quería ver (47Ronin) sigue pasando, puede ser que haya algo más que hacer?

**Comment by Cuevana** [comment]
@SepaEsteves 
A nosotros ya se nos ve bien, evidentemente porque no está cacheada la versión con codificación anterior. Si tiras el siguiente comando:
`curl -s -D - http://subs.cuevana.tv/episode/es/360/5357.srt -o /dev/null`

Deberías ver que en el response el Content-Type tiene charset ISO-8859-1. Eso ya hace que la aplicación la muestre correctamente:

```
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Mon, 23 Jun 2014 20:54:55 GMT
Content-Type: text/plain;charset=ISO-8859-1
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d3569aff4152c6869e40633a7f30263981403556895656; expires=Mon, 23-Dec-2019 23:50:00 GMT; path=/; domain=.cuevana.tv; HttpOnly
Expires: Mon, 23 Jun 2014 21:54:55 GMT
Cache-Control: public, max-age=3600
Last-Modified: Sun, 11 May 2014 19:45:01 GMT
x-goog-generation: 1399837501046000
x-goog-metageneration: 3
x-goog-stored-content-encoding: gzip
x-goog-stored-content-length: 12947
x-goog-hash: crc32c=ds18HA==
x-goog-hash: md5=4/6PnsGqGeHZHtnqj8D3wA==
x-goog-storage-class: STANDARD
Vary: Accept-Encoding
Alternate-Protocol: 80:quic
CF-RAY: 13f39565dda1096f-SCL
```

**Comment by ghost** [comment]
Arreglado el problema en mi caso. Mil gracias!

**Comment by SepaEsteves** [comment]
Alguien me puede decir como borrar la caché de la app

**Comment by maruchitas** [comment]
Hola sigo con el mismo problema de los subtitolos probe desistalar y reintalar la app pero sigue igual borre el cache del navegador y me pasa lo mismo me podran indicar como solucionarlo?

**Comment by vivicarobm** [comment]
Alguien que me ayude recien descargue la app y cuando empiezo a buscar sale este error y no se que hacer

TypeError: Cannot read property 'length' of undefined
    at t.renderGrid (app://cuevana/js/main.js:533:83)
    at callback (app://cuevana/js/main.js:486:7)
    at Request.eval [as _callback](app://cuevana/js/main.js:508:6)
    at Request.self.callback (C:\Users\VIVIAN~1\AppData\Local\Temp\nw10332_19528\node_modules\request\request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.eval (C:\Users\VIVIAN~1\AppData\Local\Temp\nw10332_19528\node_modules\request\request.js:978:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.eval (C:\Users\VIVIAN~1\AppData\Local\Temp\nw10332_19528\node_modules\request\request.js:929:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at eval (_stream_readable.js:920:16)
