### ISSUE TITLE
Soporte para linux?

### ISSUE THREAD

**Issue by opensas** [Cuevana/storm#91]
Actualmente esty corriendo popcorn 3.0 beta (la original) y funciona muy bien en ubuntu 14.04 y tambien en elementary luna (basada en ubuntu 12.04)

Está en los planes proveer una version binaria para linux?

muchas gracias

**Comment by ArnoldoRicardo** [comment]
funciona en linux, solo tienes que clonar el repositorio y seguir el README.md

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, soporta linux.
