### ISSUE TITLE
Mal comportamiento de episodios

### ISSUE THREAD

**Issue by delmicio** [Cuevana/storm#93]
Games of thrones Temporada 4 Episodio 7
    - Aparece en la sección Nuevos Episodios.
    - Aparece en la lista de episodios de la serie.
    - No aparece si uno esta en Temporada 4 Episodio 6 y hace click "Siguiente Episodio".

Grey's Anatomy Temporada 10 Episodio 24
    - Aparece en la sección Nuevos Episodios.
    - No aparece en la lista de episodios de la serie.
    - No aparece si uno esta en Temporada 10 Episodio 23 y hace click "Siguiente Episodio".

Y así pasa con varias series.

**Comment by ajatib** [comment]
Si, muchas series estan mal ordenadas e incluso tienen capitulos de otras
series dentro. Con los subtitulos pasa algo raro tb, fuera de los simbolso,
hay muchos caapitulos q no tienen y ya paso mas de una semana de q
salieron, hay algun problema con esto?

El 21 de mayo de 2014, 1:40, Emanuel Aguirre notifications@github.comescribió:

> Games of thrones Temporada 4 Episodio 7
> - Aparece en la sección Nuevos Episodios.
> - Aparece en la lista de episodios de la serie.
> - No aparece si uno esta en Temporada 4 Episodio 6 y hace click "Siguiente
>   Episodio".
> 
> Grey's Anatomy Temporada 10 Episodio 24
> - Aparece en la sección Nuevos Episodios.
> - No aparece en la lista de episodios de la serie.
> - No aparece si uno esta en Temporada 10 Episodio 23 y hace click
>   "Siguiente Episodio".
> 
> Y así pasa con varias series.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cuevana/storm/issues/93
> .

## 

Alejandro Jatib

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.
