### ISSUE TITLE
Falla en Storm Subtitulos Loading

### ISSUE THREAD

**Issue by laguardiarg** [Cuevana/storm#94]
Al día de hoy los subtitulos siguen quedando en loading y nunca se cargan...

**Comment by laguardiarg** [comment]
A alguien le esta pasando????????

**Comment by laguardiarg** [comment]
Todo el contenido cargado desde el 20/05/14 quedan con los subtitulos en loading  los demás me funcionan bien.

**Comment by kevindevm** [comment]
todavía igual

**Comment by Maxerox** [comment]
Estoy igual

**Comment by gbarzolavirtualmind** [comment]
Same, el problema esta en la server que devuelve los subtitulos. Por ej al querer cargar Frankestein  los subtitulos los carga de la siguiente url: http://subs.cuevana.tv/movie/es/720/5378.srt

tip: si se clonan la app les aparece la opcion de cargar subtitulos.

**Comment by laguardiarg** [comment]
gbarzolavirtualmind como te va?
A que te referís con clonar la aplicación?

**Comment by gbarzolavirtualmind** [comment]
Clonar, git clone y la url del repo. Ahora si queres hacer alguna contribucion hacete un fork.

El readme del repo lo explica perfectamente

**Comment by MauroJC** [comment]
Tengo problemas tambien con los subtitulos, quedan como "loading". gbarzolavirtualmind, realmente me descargue github y demas pero no comprendo el uso, no tengo experiencia al respecto, si puedes ser mas extendido a la hora de explicar te lo agradecería. Saludos!

**Comment by Cuevana** [comment]
Esto debería estar solucionado.

**Comment by laguardiarg** [comment]
Nobleza obliga. Muchas gracias. Funciona perfecto. De curioso, no voy a pretender que estoy a su nivel de programación. Cual era el problema. Saludos y nuevamente gracias.

**Comment by Maxerox** [comment]
A mi me sigue sin cargar los subtitulos :S.. tengo Windows 8.1 por si eso puede tener algo que ver.. http://screencast.com/t/Iz8t8tzIGu4A
