### ISSUE TITLE
Protector de pantalla

### ISSUE THREAD

**Issue by juanmacio** [Cuevana/storm#97]
El protector de pantalla salta mientras se reproduce el video (usando Windows 7).

No se si es problema de la app en si o del sistema en que esta construido pero estaria bueno que no suceda.

**Comment by Potencial** [comment]
a mi no me pasa, lo he probado en 5 computadores distintos con windows 7.

**Comment by juanmacio** [comment]
No perdon, no era el protector de pantalla, era que se apaga la pantalla, pero como a la media hora dejando el mouse intacto.
@Potencial, eso no te sucedio?

**Comment by carlosdlf** [comment]
Has probado quitandole la opción que dice, apagar pantalla a los 30 minuntos  (Esta en administracion de energia).

Saludos

**Comment by Cuevana** [comment]
Cerramos porque no parece ser un bug de la app, sino alguna configuración específica del OS.
